/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: s2clientprotocol/debug.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "s2clientprotocol/debug.pb-c.h"
void   sc2_apiprotocol__debug_command__init
                     (SC2APIProtocol__DebugCommand         *message)
{
  static const SC2APIProtocol__DebugCommand init_value = SC2_APIPROTOCOL__DEBUG_COMMAND__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__debug_command__get_packed_size
                     (const SC2APIProtocol__DebugCommand *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__debug_command__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__debug_command__pack
                     (const SC2APIProtocol__DebugCommand *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__debug_command__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__debug_command__pack_to_buffer
                     (const SC2APIProtocol__DebugCommand *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__debug_command__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__DebugCommand *
       sc2_apiprotocol__debug_command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__DebugCommand *)
     protobuf_c_message_unpack (&sc2_apiprotocol__debug_command__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__debug_command__free_unpacked
                     (SC2APIProtocol__DebugCommand *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__debug_command__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__debug_draw__init
                     (SC2APIProtocol__DebugDraw         *message)
{
  static const SC2APIProtocol__DebugDraw init_value = SC2_APIPROTOCOL__DEBUG_DRAW__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__debug_draw__get_packed_size
                     (const SC2APIProtocol__DebugDraw *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__debug_draw__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__debug_draw__pack
                     (const SC2APIProtocol__DebugDraw *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__debug_draw__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__debug_draw__pack_to_buffer
                     (const SC2APIProtocol__DebugDraw *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__debug_draw__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__DebugDraw *
       sc2_apiprotocol__debug_draw__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__DebugDraw *)
     protobuf_c_message_unpack (&sc2_apiprotocol__debug_draw__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__debug_draw__free_unpacked
                     (SC2APIProtocol__DebugDraw *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__debug_draw__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__line__init
                     (SC2APIProtocol__Line         *message)
{
  static const SC2APIProtocol__Line init_value = SC2_APIPROTOCOL__LINE__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__line__get_packed_size
                     (const SC2APIProtocol__Line *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__line__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__line__pack
                     (const SC2APIProtocol__Line *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__line__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__line__pack_to_buffer
                     (const SC2APIProtocol__Line *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__line__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__Line *
       sc2_apiprotocol__line__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__Line *)
     protobuf_c_message_unpack (&sc2_apiprotocol__line__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__line__free_unpacked
                     (SC2APIProtocol__Line *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__line__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__color__init
                     (SC2APIProtocol__Color         *message)
{
  static const SC2APIProtocol__Color init_value = SC2_APIPROTOCOL__COLOR__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__color__get_packed_size
                     (const SC2APIProtocol__Color *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__color__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__color__pack
                     (const SC2APIProtocol__Color *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__color__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__color__pack_to_buffer
                     (const SC2APIProtocol__Color *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__color__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__Color *
       sc2_apiprotocol__color__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__Color *)
     protobuf_c_message_unpack (&sc2_apiprotocol__color__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__color__free_unpacked
                     (SC2APIProtocol__Color *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__color__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__debug_text__init
                     (SC2APIProtocol__DebugText         *message)
{
  static const SC2APIProtocol__DebugText init_value = SC2_APIPROTOCOL__DEBUG_TEXT__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__debug_text__get_packed_size
                     (const SC2APIProtocol__DebugText *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__debug_text__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__debug_text__pack
                     (const SC2APIProtocol__DebugText *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__debug_text__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__debug_text__pack_to_buffer
                     (const SC2APIProtocol__DebugText *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__debug_text__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__DebugText *
       sc2_apiprotocol__debug_text__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__DebugText *)
     protobuf_c_message_unpack (&sc2_apiprotocol__debug_text__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__debug_text__free_unpacked
                     (SC2APIProtocol__DebugText *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__debug_text__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__debug_line__init
                     (SC2APIProtocol__DebugLine         *message)
{
  static const SC2APIProtocol__DebugLine init_value = SC2_APIPROTOCOL__DEBUG_LINE__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__debug_line__get_packed_size
                     (const SC2APIProtocol__DebugLine *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__debug_line__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__debug_line__pack
                     (const SC2APIProtocol__DebugLine *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__debug_line__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__debug_line__pack_to_buffer
                     (const SC2APIProtocol__DebugLine *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__debug_line__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__DebugLine *
       sc2_apiprotocol__debug_line__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__DebugLine *)
     protobuf_c_message_unpack (&sc2_apiprotocol__debug_line__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__debug_line__free_unpacked
                     (SC2APIProtocol__DebugLine *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__debug_line__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__debug_box__init
                     (SC2APIProtocol__DebugBox         *message)
{
  static const SC2APIProtocol__DebugBox init_value = SC2_APIPROTOCOL__DEBUG_BOX__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__debug_box__get_packed_size
                     (const SC2APIProtocol__DebugBox *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__debug_box__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__debug_box__pack
                     (const SC2APIProtocol__DebugBox *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__debug_box__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__debug_box__pack_to_buffer
                     (const SC2APIProtocol__DebugBox *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__debug_box__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__DebugBox *
       sc2_apiprotocol__debug_box__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__DebugBox *)
     protobuf_c_message_unpack (&sc2_apiprotocol__debug_box__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__debug_box__free_unpacked
                     (SC2APIProtocol__DebugBox *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__debug_box__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__debug_sphere__init
                     (SC2APIProtocol__DebugSphere         *message)
{
  static const SC2APIProtocol__DebugSphere init_value = SC2_APIPROTOCOL__DEBUG_SPHERE__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__debug_sphere__get_packed_size
                     (const SC2APIProtocol__DebugSphere *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__debug_sphere__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__debug_sphere__pack
                     (const SC2APIProtocol__DebugSphere *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__debug_sphere__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__debug_sphere__pack_to_buffer
                     (const SC2APIProtocol__DebugSphere *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__debug_sphere__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__DebugSphere *
       sc2_apiprotocol__debug_sphere__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__DebugSphere *)
     protobuf_c_message_unpack (&sc2_apiprotocol__debug_sphere__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__debug_sphere__free_unpacked
                     (SC2APIProtocol__DebugSphere *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__debug_sphere__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__debug_create_unit__init
                     (SC2APIProtocol__DebugCreateUnit         *message)
{
  static const SC2APIProtocol__DebugCreateUnit init_value = SC2_APIPROTOCOL__DEBUG_CREATE_UNIT__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__debug_create_unit__get_packed_size
                     (const SC2APIProtocol__DebugCreateUnit *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__debug_create_unit__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__debug_create_unit__pack
                     (const SC2APIProtocol__DebugCreateUnit *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__debug_create_unit__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__debug_create_unit__pack_to_buffer
                     (const SC2APIProtocol__DebugCreateUnit *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__debug_create_unit__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__DebugCreateUnit *
       sc2_apiprotocol__debug_create_unit__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__DebugCreateUnit *)
     protobuf_c_message_unpack (&sc2_apiprotocol__debug_create_unit__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__debug_create_unit__free_unpacked
                     (SC2APIProtocol__DebugCreateUnit *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__debug_create_unit__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__debug_kill_unit__init
                     (SC2APIProtocol__DebugKillUnit         *message)
{
  static const SC2APIProtocol__DebugKillUnit init_value = SC2_APIPROTOCOL__DEBUG_KILL_UNIT__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__debug_kill_unit__get_packed_size
                     (const SC2APIProtocol__DebugKillUnit *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__debug_kill_unit__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__debug_kill_unit__pack
                     (const SC2APIProtocol__DebugKillUnit *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__debug_kill_unit__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__debug_kill_unit__pack_to_buffer
                     (const SC2APIProtocol__DebugKillUnit *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__debug_kill_unit__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__DebugKillUnit *
       sc2_apiprotocol__debug_kill_unit__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__DebugKillUnit *)
     protobuf_c_message_unpack (&sc2_apiprotocol__debug_kill_unit__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__debug_kill_unit__free_unpacked
                     (SC2APIProtocol__DebugKillUnit *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__debug_kill_unit__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__debug_test_process__init
                     (SC2APIProtocol__DebugTestProcess         *message)
{
  static const SC2APIProtocol__DebugTestProcess init_value = SC2_APIPROTOCOL__DEBUG_TEST_PROCESS__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__debug_test_process__get_packed_size
                     (const SC2APIProtocol__DebugTestProcess *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__debug_test_process__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__debug_test_process__pack
                     (const SC2APIProtocol__DebugTestProcess *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__debug_test_process__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__debug_test_process__pack_to_buffer
                     (const SC2APIProtocol__DebugTestProcess *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__debug_test_process__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__DebugTestProcess *
       sc2_apiprotocol__debug_test_process__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__DebugTestProcess *)
     protobuf_c_message_unpack (&sc2_apiprotocol__debug_test_process__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__debug_test_process__free_unpacked
                     (SC2APIProtocol__DebugTestProcess *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__debug_test_process__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__debug_set_score__init
                     (SC2APIProtocol__DebugSetScore         *message)
{
  static const SC2APIProtocol__DebugSetScore init_value = SC2_APIPROTOCOL__DEBUG_SET_SCORE__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__debug_set_score__get_packed_size
                     (const SC2APIProtocol__DebugSetScore *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__debug_set_score__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__debug_set_score__pack
                     (const SC2APIProtocol__DebugSetScore *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__debug_set_score__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__debug_set_score__pack_to_buffer
                     (const SC2APIProtocol__DebugSetScore *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__debug_set_score__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__DebugSetScore *
       sc2_apiprotocol__debug_set_score__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__DebugSetScore *)
     protobuf_c_message_unpack (&sc2_apiprotocol__debug_set_score__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__debug_set_score__free_unpacked
                     (SC2APIProtocol__DebugSetScore *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__debug_set_score__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__debug_end_game__init
                     (SC2APIProtocol__DebugEndGame         *message)
{
  static const SC2APIProtocol__DebugEndGame init_value = SC2_APIPROTOCOL__DEBUG_END_GAME__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__debug_end_game__get_packed_size
                     (const SC2APIProtocol__DebugEndGame *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__debug_end_game__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__debug_end_game__pack
                     (const SC2APIProtocol__DebugEndGame *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__debug_end_game__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__debug_end_game__pack_to_buffer
                     (const SC2APIProtocol__DebugEndGame *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__debug_end_game__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__DebugEndGame *
       sc2_apiprotocol__debug_end_game__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__DebugEndGame *)
     protobuf_c_message_unpack (&sc2_apiprotocol__debug_end_game__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__debug_end_game__free_unpacked
                     (SC2APIProtocol__DebugEndGame *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__debug_end_game__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__debug_set_unit_value__init
                     (SC2APIProtocol__DebugSetUnitValue         *message)
{
  static const SC2APIProtocol__DebugSetUnitValue init_value = SC2_APIPROTOCOL__DEBUG_SET_UNIT_VALUE__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__debug_set_unit_value__get_packed_size
                     (const SC2APIProtocol__DebugSetUnitValue *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__debug_set_unit_value__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__debug_set_unit_value__pack
                     (const SC2APIProtocol__DebugSetUnitValue *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__debug_set_unit_value__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__debug_set_unit_value__pack_to_buffer
                     (const SC2APIProtocol__DebugSetUnitValue *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__debug_set_unit_value__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__DebugSetUnitValue *
       sc2_apiprotocol__debug_set_unit_value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__DebugSetUnitValue *)
     protobuf_c_message_unpack (&sc2_apiprotocol__debug_set_unit_value__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__debug_set_unit_value__free_unpacked
                     (SC2APIProtocol__DebugSetUnitValue *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__debug_set_unit_value__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor sc2_apiprotocol__debug_command__field_descriptors[8] =
{
  {
    "draw",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__DebugCommand, command_case),
    offsetof(SC2APIProtocol__DebugCommand, draw),
    &sc2_apiprotocol__debug_draw__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "game_state",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(SC2APIProtocol__DebugCommand, command_case),
    offsetof(SC2APIProtocol__DebugCommand, game_state),
    &sc2_apiprotocol__debug_game_state__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "create_unit",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__DebugCommand, command_case),
    offsetof(SC2APIProtocol__DebugCommand, create_unit),
    &sc2_apiprotocol__debug_create_unit__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kill_unit",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__DebugCommand, command_case),
    offsetof(SC2APIProtocol__DebugCommand, kill_unit),
    &sc2_apiprotocol__debug_kill_unit__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "test_process",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__DebugCommand, command_case),
    offsetof(SC2APIProtocol__DebugCommand, test_process),
    &sc2_apiprotocol__debug_test_process__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "score",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__DebugCommand, command_case),
    offsetof(SC2APIProtocol__DebugCommand, score),
    &sc2_apiprotocol__debug_set_score__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end_game",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__DebugCommand, command_case),
    offsetof(SC2APIProtocol__DebugCommand, end_game),
    &sc2_apiprotocol__debug_end_game__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unit_value",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__DebugCommand, command_case),
    offsetof(SC2APIProtocol__DebugCommand, unit_value),
    &sc2_apiprotocol__debug_set_unit_value__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__debug_command__field_indices_by_name[] = {
  2,   /* field[2] = create_unit */
  0,   /* field[0] = draw */
  6,   /* field[6] = end_game */
  1,   /* field[1] = game_state */
  3,   /* field[3] = kill_unit */
  5,   /* field[5] = score */
  4,   /* field[4] = test_process */
  7,   /* field[7] = unit_value */
};
static const ProtobufCIntRange sc2_apiprotocol__debug_command__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__debug_command__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.DebugCommand",
  "DebugCommand",
  "SC2APIProtocol__DebugCommand",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__DebugCommand),
  8,
  sc2_apiprotocol__debug_command__field_descriptors,
  sc2_apiprotocol__debug_command__field_indices_by_name,
  1,  sc2_apiprotocol__debug_command__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__debug_command__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__debug_draw__field_descriptors[4] =
{
  {
    "text",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__DebugDraw, n_text),
    offsetof(SC2APIProtocol__DebugDraw, text),
    &sc2_apiprotocol__debug_text__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lines",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__DebugDraw, n_lines),
    offsetof(SC2APIProtocol__DebugDraw, lines),
    &sc2_apiprotocol__debug_line__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "boxes",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__DebugDraw, n_boxes),
    offsetof(SC2APIProtocol__DebugDraw, boxes),
    &sc2_apiprotocol__debug_box__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "spheres",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__DebugDraw, n_spheres),
    offsetof(SC2APIProtocol__DebugDraw, spheres),
    &sc2_apiprotocol__debug_sphere__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__debug_draw__field_indices_by_name[] = {
  2,   /* field[2] = boxes */
  1,   /* field[1] = lines */
  3,   /* field[3] = spheres */
  0,   /* field[0] = text */
};
static const ProtobufCIntRange sc2_apiprotocol__debug_draw__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__debug_draw__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.DebugDraw",
  "DebugDraw",
  "SC2APIProtocol__DebugDraw",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__DebugDraw),
  4,
  sc2_apiprotocol__debug_draw__field_descriptors,
  sc2_apiprotocol__debug_draw__field_indices_by_name,
  1,  sc2_apiprotocol__debug_draw__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__debug_draw__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__line__field_descriptors[2] =
{
  {
    "p0",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__Line, p0),
    &sc2_apiprotocol__point__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "p1",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__Line, p1),
    &sc2_apiprotocol__point__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__line__field_indices_by_name[] = {
  0,   /* field[0] = p0 */
  1,   /* field[1] = p1 */
};
static const ProtobufCIntRange sc2_apiprotocol__line__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__line__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.Line",
  "Line",
  "SC2APIProtocol__Line",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__Line),
  2,
  sc2_apiprotocol__line__field_descriptors,
  sc2_apiprotocol__line__field_indices_by_name,
  1,  sc2_apiprotocol__line__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__line__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__color__field_descriptors[3] =
{
  {
    "r",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SC2APIProtocol__Color, has_r),
    offsetof(SC2APIProtocol__Color, r),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "g",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SC2APIProtocol__Color, has_g),
    offsetof(SC2APIProtocol__Color, g),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "b",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SC2APIProtocol__Color, has_b),
    offsetof(SC2APIProtocol__Color, b),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__color__field_indices_by_name[] = {
  2,   /* field[2] = b */
  1,   /* field[1] = g */
  0,   /* field[0] = r */
};
static const ProtobufCIntRange sc2_apiprotocol__color__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__color__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.Color",
  "Color",
  "SC2APIProtocol__Color",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__Color),
  3,
  sc2_apiprotocol__color__field_descriptors,
  sc2_apiprotocol__color__field_indices_by_name,
  1,  sc2_apiprotocol__color__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__color__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__debug_text__field_descriptors[5] =
{
  {
    "color",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__DebugText, color),
    &sc2_apiprotocol__color__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "text",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__DebugText, text),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "virtual_pos",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__DebugText, virtual_pos),
    &sc2_apiprotocol__point__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "world_pos",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__DebugText, world_pos),
    &sc2_apiprotocol__point__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SC2APIProtocol__DebugText, has_size),
    offsetof(SC2APIProtocol__DebugText, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__debug_text__field_indices_by_name[] = {
  0,   /* field[0] = color */
  4,   /* field[4] = size */
  1,   /* field[1] = text */
  2,   /* field[2] = virtual_pos */
  3,   /* field[3] = world_pos */
};
static const ProtobufCIntRange sc2_apiprotocol__debug_text__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__debug_text__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.DebugText",
  "DebugText",
  "SC2APIProtocol__DebugText",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__DebugText),
  5,
  sc2_apiprotocol__debug_text__field_descriptors,
  sc2_apiprotocol__debug_text__field_indices_by_name,
  1,  sc2_apiprotocol__debug_text__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__debug_text__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__debug_line__field_descriptors[2] =
{
  {
    "color",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__DebugLine, color),
    &sc2_apiprotocol__color__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "line",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__DebugLine, line),
    &sc2_apiprotocol__line__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__debug_line__field_indices_by_name[] = {
  0,   /* field[0] = color */
  1,   /* field[1] = line */
};
static const ProtobufCIntRange sc2_apiprotocol__debug_line__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__debug_line__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.DebugLine",
  "DebugLine",
  "SC2APIProtocol__DebugLine",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__DebugLine),
  2,
  sc2_apiprotocol__debug_line__field_descriptors,
  sc2_apiprotocol__debug_line__field_indices_by_name,
  1,  sc2_apiprotocol__debug_line__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__debug_line__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__debug_box__field_descriptors[3] =
{
  {
    "color",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__DebugBox, color),
    &sc2_apiprotocol__color__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "min",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__DebugBox, min),
    &sc2_apiprotocol__point__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__DebugBox, max),
    &sc2_apiprotocol__point__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__debug_box__field_indices_by_name[] = {
  0,   /* field[0] = color */
  2,   /* field[2] = max */
  1,   /* field[1] = min */
};
static const ProtobufCIntRange sc2_apiprotocol__debug_box__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__debug_box__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.DebugBox",
  "DebugBox",
  "SC2APIProtocol__DebugBox",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__DebugBox),
  3,
  sc2_apiprotocol__debug_box__field_descriptors,
  sc2_apiprotocol__debug_box__field_indices_by_name,
  1,  sc2_apiprotocol__debug_box__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__debug_box__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__debug_sphere__field_descriptors[3] =
{
  {
    "color",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__DebugSphere, color),
    &sc2_apiprotocol__color__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "p",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__DebugSphere, p),
    &sc2_apiprotocol__point__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__DebugSphere, has_r),
    offsetof(SC2APIProtocol__DebugSphere, r),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__debug_sphere__field_indices_by_name[] = {
  0,   /* field[0] = color */
  1,   /* field[1] = p */
  2,   /* field[2] = r */
};
static const ProtobufCIntRange sc2_apiprotocol__debug_sphere__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__debug_sphere__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.DebugSphere",
  "DebugSphere",
  "SC2APIProtocol__DebugSphere",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__DebugSphere),
  3,
  sc2_apiprotocol__debug_sphere__field_descriptors,
  sc2_apiprotocol__debug_sphere__field_indices_by_name,
  1,  sc2_apiprotocol__debug_sphere__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__debug_sphere__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__debug_create_unit__field_descriptors[4] =
{
  {
    "unit_type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SC2APIProtocol__DebugCreateUnit, has_unit_type),
    offsetof(SC2APIProtocol__DebugCreateUnit, unit_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "owner",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SC2APIProtocol__DebugCreateUnit, has_owner),
    offsetof(SC2APIProtocol__DebugCreateUnit, owner),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__DebugCreateUnit, pos),
    &sc2_apiprotocol__point2_d__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "quantity",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SC2APIProtocol__DebugCreateUnit, has_quantity),
    offsetof(SC2APIProtocol__DebugCreateUnit, quantity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__debug_create_unit__field_indices_by_name[] = {
  1,   /* field[1] = owner */
  2,   /* field[2] = pos */
  3,   /* field[3] = quantity */
  0,   /* field[0] = unit_type */
};
static const ProtobufCIntRange sc2_apiprotocol__debug_create_unit__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__debug_create_unit__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.DebugCreateUnit",
  "DebugCreateUnit",
  "SC2APIProtocol__DebugCreateUnit",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__DebugCreateUnit),
  4,
  sc2_apiprotocol__debug_create_unit__field_descriptors,
  sc2_apiprotocol__debug_create_unit__field_indices_by_name,
  1,  sc2_apiprotocol__debug_create_unit__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__debug_create_unit__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__debug_kill_unit__field_descriptors[1] =
{
  {
    "tag",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(SC2APIProtocol__DebugKillUnit, n_tag),
    offsetof(SC2APIProtocol__DebugKillUnit, tag),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__debug_kill_unit__field_indices_by_name[] = {
  0,   /* field[0] = tag */
};
static const ProtobufCIntRange sc2_apiprotocol__debug_kill_unit__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__debug_kill_unit__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.DebugKillUnit",
  "DebugKillUnit",
  "SC2APIProtocol__DebugKillUnit",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__DebugKillUnit),
  1,
  sc2_apiprotocol__debug_kill_unit__field_descriptors,
  sc2_apiprotocol__debug_kill_unit__field_indices_by_name,
  1,  sc2_apiprotocol__debug_kill_unit__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__debug_kill_unit__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue sc2_apiprotocol__debug_test_process__test__enum_values_by_number[3] =
{
  { "hang", "SC2_APIPROTOCOL__DEBUG_TEST_PROCESS__TEST__hang", 1 },
  { "crash", "SC2_APIPROTOCOL__DEBUG_TEST_PROCESS__TEST__crash", 2 },
  { "exit", "SC2_APIPROTOCOL__DEBUG_TEST_PROCESS__TEST__exit", 3 },
};
static const ProtobufCIntRange sc2_apiprotocol__debug_test_process__test__value_ranges[] = {
{1, 0},{0, 3}
};
static const ProtobufCEnumValueIndex sc2_apiprotocol__debug_test_process__test__enum_values_by_name[3] =
{
  { "crash", 1 },
  { "exit", 2 },
  { "hang", 0 },
};
const ProtobufCEnumDescriptor sc2_apiprotocol__debug_test_process__test__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.DebugTestProcess.Test",
  "Test",
  "SC2APIProtocol__DebugTestProcess__Test",
  "SC2APIProtocol",
  3,
  sc2_apiprotocol__debug_test_process__test__enum_values_by_number,
  3,
  sc2_apiprotocol__debug_test_process__test__enum_values_by_name,
  1,
  sc2_apiprotocol__debug_test_process__test__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__debug_test_process__field_descriptors[2] =
{
  {
    "test",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(SC2APIProtocol__DebugTestProcess, has_test),
    offsetof(SC2APIProtocol__DebugTestProcess, test),
    &sc2_apiprotocol__debug_test_process__test__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "delay_ms",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SC2APIProtocol__DebugTestProcess, has_delay_ms),
    offsetof(SC2APIProtocol__DebugTestProcess, delay_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__debug_test_process__field_indices_by_name[] = {
  1,   /* field[1] = delay_ms */
  0,   /* field[0] = test */
};
static const ProtobufCIntRange sc2_apiprotocol__debug_test_process__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__debug_test_process__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.DebugTestProcess",
  "DebugTestProcess",
  "SC2APIProtocol__DebugTestProcess",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__DebugTestProcess),
  2,
  sc2_apiprotocol__debug_test_process__field_descriptors,
  sc2_apiprotocol__debug_test_process__field_indices_by_name,
  1,  sc2_apiprotocol__debug_test_process__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__debug_test_process__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__debug_set_score__field_descriptors[1] =
{
  {
    "score",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__DebugSetScore, has_score),
    offsetof(SC2APIProtocol__DebugSetScore, score),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__debug_set_score__field_indices_by_name[] = {
  0,   /* field[0] = score */
};
static const ProtobufCIntRange sc2_apiprotocol__debug_set_score__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__debug_set_score__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.DebugSetScore",
  "DebugSetScore",
  "SC2APIProtocol__DebugSetScore",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__DebugSetScore),
  1,
  sc2_apiprotocol__debug_set_score__field_descriptors,
  sc2_apiprotocol__debug_set_score__field_indices_by_name,
  1,  sc2_apiprotocol__debug_set_score__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__debug_set_score__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue sc2_apiprotocol__debug_end_game__end_result__enum_values_by_number[2] =
{
  { "Surrender", "SC2_APIPROTOCOL__DEBUG_END_GAME__END_RESULT__Surrender", 1 },
  { "DeclareVictory", "SC2_APIPROTOCOL__DEBUG_END_GAME__END_RESULT__DeclareVictory", 2 },
};
static const ProtobufCIntRange sc2_apiprotocol__debug_end_game__end_result__value_ranges[] = {
{1, 0},{0, 2}
};
static const ProtobufCEnumValueIndex sc2_apiprotocol__debug_end_game__end_result__enum_values_by_name[2] =
{
  { "DeclareVictory", 1 },
  { "Surrender", 0 },
};
const ProtobufCEnumDescriptor sc2_apiprotocol__debug_end_game__end_result__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.DebugEndGame.EndResult",
  "EndResult",
  "SC2APIProtocol__DebugEndGame__EndResult",
  "SC2APIProtocol",
  2,
  sc2_apiprotocol__debug_end_game__end_result__enum_values_by_number,
  2,
  sc2_apiprotocol__debug_end_game__end_result__enum_values_by_name,
  1,
  sc2_apiprotocol__debug_end_game__end_result__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__debug_end_game__field_descriptors[1] =
{
  {
    "end_result",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(SC2APIProtocol__DebugEndGame, has_end_result),
    offsetof(SC2APIProtocol__DebugEndGame, end_result),
    &sc2_apiprotocol__debug_end_game__end_result__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__debug_end_game__field_indices_by_name[] = {
  0,   /* field[0] = end_result */
};
static const ProtobufCIntRange sc2_apiprotocol__debug_end_game__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__debug_end_game__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.DebugEndGame",
  "DebugEndGame",
  "SC2APIProtocol__DebugEndGame",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__DebugEndGame),
  1,
  sc2_apiprotocol__debug_end_game__field_descriptors,
  sc2_apiprotocol__debug_end_game__field_indices_by_name,
  1,  sc2_apiprotocol__debug_end_game__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__debug_end_game__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue sc2_apiprotocol__debug_set_unit_value__unit_value__enum_values_by_number[3] =
{
  { "Energy", "SC2_APIPROTOCOL__DEBUG_SET_UNIT_VALUE__UNIT_VALUE__Energy", 1 },
  { "Life", "SC2_APIPROTOCOL__DEBUG_SET_UNIT_VALUE__UNIT_VALUE__Life", 2 },
  { "Shields", "SC2_APIPROTOCOL__DEBUG_SET_UNIT_VALUE__UNIT_VALUE__Shields", 3 },
};
static const ProtobufCIntRange sc2_apiprotocol__debug_set_unit_value__unit_value__value_ranges[] = {
{1, 0},{0, 3}
};
static const ProtobufCEnumValueIndex sc2_apiprotocol__debug_set_unit_value__unit_value__enum_values_by_name[3] =
{
  { "Energy", 0 },
  { "Life", 1 },
  { "Shields", 2 },
};
const ProtobufCEnumDescriptor sc2_apiprotocol__debug_set_unit_value__unit_value__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.DebugSetUnitValue.UnitValue",
  "UnitValue",
  "SC2APIProtocol__DebugSetUnitValue__UnitValue",
  "SC2APIProtocol",
  3,
  sc2_apiprotocol__debug_set_unit_value__unit_value__enum_values_by_number,
  3,
  sc2_apiprotocol__debug_set_unit_value__unit_value__enum_values_by_name,
  1,
  sc2_apiprotocol__debug_set_unit_value__unit_value__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__debug_set_unit_value__field_descriptors[3] =
{
  {
    "unit_value",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(SC2APIProtocol__DebugSetUnitValue, has_unit_value),
    offsetof(SC2APIProtocol__DebugSetUnitValue, unit_value),
    &sc2_apiprotocol__debug_set_unit_value__unit_value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__DebugSetUnitValue, has_value),
    offsetof(SC2APIProtocol__DebugSetUnitValue, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unit_tag",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(SC2APIProtocol__DebugSetUnitValue, has_unit_tag),
    offsetof(SC2APIProtocol__DebugSetUnitValue, unit_tag),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__debug_set_unit_value__field_indices_by_name[] = {
  2,   /* field[2] = unit_tag */
  0,   /* field[0] = unit_value */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange sc2_apiprotocol__debug_set_unit_value__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__debug_set_unit_value__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.DebugSetUnitValue",
  "DebugSetUnitValue",
  "SC2APIProtocol__DebugSetUnitValue",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__DebugSetUnitValue),
  3,
  sc2_apiprotocol__debug_set_unit_value__field_descriptors,
  sc2_apiprotocol__debug_set_unit_value__field_indices_by_name,
  1,  sc2_apiprotocol__debug_set_unit_value__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__debug_set_unit_value__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue sc2_apiprotocol__debug_game_state__enum_values_by_number[12] =
{
  { "show_map", "SC2_APIPROTOCOL__DEBUG_GAME_STATE__show_map", 1 },
  { "control_enemy", "SC2_APIPROTOCOL__DEBUG_GAME_STATE__control_enemy", 2 },
  { "food", "SC2_APIPROTOCOL__DEBUG_GAME_STATE__food", 3 },
  { "free", "SC2_APIPROTOCOL__DEBUG_GAME_STATE__free", 4 },
  { "all_resources", "SC2_APIPROTOCOL__DEBUG_GAME_STATE__all_resources", 5 },
  { "god", "SC2_APIPROTOCOL__DEBUG_GAME_STATE__god", 6 },
  { "minerals", "SC2_APIPROTOCOL__DEBUG_GAME_STATE__minerals", 7 },
  { "gas", "SC2_APIPROTOCOL__DEBUG_GAME_STATE__gas", 8 },
  { "cooldown", "SC2_APIPROTOCOL__DEBUG_GAME_STATE__cooldown", 9 },
  { "tech_tree", "SC2_APIPROTOCOL__DEBUG_GAME_STATE__tech_tree", 10 },
  { "upgrade", "SC2_APIPROTOCOL__DEBUG_GAME_STATE__upgrade", 11 },
  { "fast_build", "SC2_APIPROTOCOL__DEBUG_GAME_STATE__fast_build", 12 },
};
static const ProtobufCIntRange sc2_apiprotocol__debug_game_state__value_ranges[] = {
{1, 0},{0, 12}
};
static const ProtobufCEnumValueIndex sc2_apiprotocol__debug_game_state__enum_values_by_name[12] =
{
  { "all_resources", 4 },
  { "control_enemy", 1 },
  { "cooldown", 8 },
  { "fast_build", 11 },
  { "food", 2 },
  { "free", 3 },
  { "gas", 7 },
  { "god", 5 },
  { "minerals", 6 },
  { "show_map", 0 },
  { "tech_tree", 9 },
  { "upgrade", 10 },
};
const ProtobufCEnumDescriptor sc2_apiprotocol__debug_game_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.DebugGameState",
  "DebugGameState",
  "SC2APIProtocol__DebugGameState",
  "SC2APIProtocol",
  12,
  sc2_apiprotocol__debug_game_state__enum_values_by_number,
  12,
  sc2_apiprotocol__debug_game_state__enum_values_by_name,
  1,
  sc2_apiprotocol__debug_game_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
