/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: s2clientprotocol/query.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "s2clientprotocol/query.pb-c.h"
void   sc2_apiprotocol__request_query__init
                     (SC2APIProtocol__RequestQuery         *message)
{
  static const SC2APIProtocol__RequestQuery init_value = SC2_APIPROTOCOL__REQUEST_QUERY__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__request_query__get_packed_size
                     (const SC2APIProtocol__RequestQuery *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__request_query__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__request_query__pack
                     (const SC2APIProtocol__RequestQuery *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__request_query__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__request_query__pack_to_buffer
                     (const SC2APIProtocol__RequestQuery *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__request_query__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__RequestQuery *
       sc2_apiprotocol__request_query__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__RequestQuery *)
     protobuf_c_message_unpack (&sc2_apiprotocol__request_query__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__request_query__free_unpacked
                     (SC2APIProtocol__RequestQuery *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__request_query__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__response_query__init
                     (SC2APIProtocol__ResponseQuery         *message)
{
  static const SC2APIProtocol__ResponseQuery init_value = SC2_APIPROTOCOL__RESPONSE_QUERY__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__response_query__get_packed_size
                     (const SC2APIProtocol__ResponseQuery *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__response_query__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__response_query__pack
                     (const SC2APIProtocol__ResponseQuery *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__response_query__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__response_query__pack_to_buffer
                     (const SC2APIProtocol__ResponseQuery *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__response_query__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__ResponseQuery *
       sc2_apiprotocol__response_query__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__ResponseQuery *)
     protobuf_c_message_unpack (&sc2_apiprotocol__response_query__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__response_query__free_unpacked
                     (SC2APIProtocol__ResponseQuery *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__response_query__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__request_query_pathing__init
                     (SC2APIProtocol__RequestQueryPathing         *message)
{
  static const SC2APIProtocol__RequestQueryPathing init_value = SC2_APIPROTOCOL__REQUEST_QUERY_PATHING__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__request_query_pathing__get_packed_size
                     (const SC2APIProtocol__RequestQueryPathing *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__request_query_pathing__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__request_query_pathing__pack
                     (const SC2APIProtocol__RequestQueryPathing *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__request_query_pathing__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__request_query_pathing__pack_to_buffer
                     (const SC2APIProtocol__RequestQueryPathing *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__request_query_pathing__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__RequestQueryPathing *
       sc2_apiprotocol__request_query_pathing__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__RequestQueryPathing *)
     protobuf_c_message_unpack (&sc2_apiprotocol__request_query_pathing__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__request_query_pathing__free_unpacked
                     (SC2APIProtocol__RequestQueryPathing *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__request_query_pathing__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__response_query_pathing__init
                     (SC2APIProtocol__ResponseQueryPathing         *message)
{
  static const SC2APIProtocol__ResponseQueryPathing init_value = SC2_APIPROTOCOL__RESPONSE_QUERY_PATHING__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__response_query_pathing__get_packed_size
                     (const SC2APIProtocol__ResponseQueryPathing *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__response_query_pathing__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__response_query_pathing__pack
                     (const SC2APIProtocol__ResponseQueryPathing *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__response_query_pathing__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__response_query_pathing__pack_to_buffer
                     (const SC2APIProtocol__ResponseQueryPathing *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__response_query_pathing__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__ResponseQueryPathing *
       sc2_apiprotocol__response_query_pathing__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__ResponseQueryPathing *)
     protobuf_c_message_unpack (&sc2_apiprotocol__response_query_pathing__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__response_query_pathing__free_unpacked
                     (SC2APIProtocol__ResponseQueryPathing *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__response_query_pathing__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__request_query_available_abilities__init
                     (SC2APIProtocol__RequestQueryAvailableAbilities         *message)
{
  static const SC2APIProtocol__RequestQueryAvailableAbilities init_value = SC2_APIPROTOCOL__REQUEST_QUERY_AVAILABLE_ABILITIES__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__request_query_available_abilities__get_packed_size
                     (const SC2APIProtocol__RequestQueryAvailableAbilities *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__request_query_available_abilities__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__request_query_available_abilities__pack
                     (const SC2APIProtocol__RequestQueryAvailableAbilities *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__request_query_available_abilities__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__request_query_available_abilities__pack_to_buffer
                     (const SC2APIProtocol__RequestQueryAvailableAbilities *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__request_query_available_abilities__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__RequestQueryAvailableAbilities *
       sc2_apiprotocol__request_query_available_abilities__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__RequestQueryAvailableAbilities *)
     protobuf_c_message_unpack (&sc2_apiprotocol__request_query_available_abilities__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__request_query_available_abilities__free_unpacked
                     (SC2APIProtocol__RequestQueryAvailableAbilities *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__request_query_available_abilities__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__response_query_available_abilities__init
                     (SC2APIProtocol__ResponseQueryAvailableAbilities         *message)
{
  static const SC2APIProtocol__ResponseQueryAvailableAbilities init_value = SC2_APIPROTOCOL__RESPONSE_QUERY_AVAILABLE_ABILITIES__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__response_query_available_abilities__get_packed_size
                     (const SC2APIProtocol__ResponseQueryAvailableAbilities *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__response_query_available_abilities__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__response_query_available_abilities__pack
                     (const SC2APIProtocol__ResponseQueryAvailableAbilities *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__response_query_available_abilities__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__response_query_available_abilities__pack_to_buffer
                     (const SC2APIProtocol__ResponseQueryAvailableAbilities *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__response_query_available_abilities__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__ResponseQueryAvailableAbilities *
       sc2_apiprotocol__response_query_available_abilities__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__ResponseQueryAvailableAbilities *)
     protobuf_c_message_unpack (&sc2_apiprotocol__response_query_available_abilities__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__response_query_available_abilities__free_unpacked
                     (SC2APIProtocol__ResponseQueryAvailableAbilities *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__response_query_available_abilities__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__request_query_building_placement__init
                     (SC2APIProtocol__RequestQueryBuildingPlacement         *message)
{
  static const SC2APIProtocol__RequestQueryBuildingPlacement init_value = SC2_APIPROTOCOL__REQUEST_QUERY_BUILDING_PLACEMENT__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__request_query_building_placement__get_packed_size
                     (const SC2APIProtocol__RequestQueryBuildingPlacement *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__request_query_building_placement__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__request_query_building_placement__pack
                     (const SC2APIProtocol__RequestQueryBuildingPlacement *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__request_query_building_placement__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__request_query_building_placement__pack_to_buffer
                     (const SC2APIProtocol__RequestQueryBuildingPlacement *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__request_query_building_placement__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__RequestQueryBuildingPlacement *
       sc2_apiprotocol__request_query_building_placement__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__RequestQueryBuildingPlacement *)
     protobuf_c_message_unpack (&sc2_apiprotocol__request_query_building_placement__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__request_query_building_placement__free_unpacked
                     (SC2APIProtocol__RequestQueryBuildingPlacement *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__request_query_building_placement__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__response_query_building_placement__init
                     (SC2APIProtocol__ResponseQueryBuildingPlacement         *message)
{
  static const SC2APIProtocol__ResponseQueryBuildingPlacement init_value = SC2_APIPROTOCOL__RESPONSE_QUERY_BUILDING_PLACEMENT__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__response_query_building_placement__get_packed_size
                     (const SC2APIProtocol__ResponseQueryBuildingPlacement *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__response_query_building_placement__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__response_query_building_placement__pack
                     (const SC2APIProtocol__ResponseQueryBuildingPlacement *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__response_query_building_placement__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__response_query_building_placement__pack_to_buffer
                     (const SC2APIProtocol__ResponseQueryBuildingPlacement *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__response_query_building_placement__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__ResponseQueryBuildingPlacement *
       sc2_apiprotocol__response_query_building_placement__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__ResponseQueryBuildingPlacement *)
     protobuf_c_message_unpack (&sc2_apiprotocol__response_query_building_placement__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__response_query_building_placement__free_unpacked
                     (SC2APIProtocol__ResponseQueryBuildingPlacement *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__response_query_building_placement__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor sc2_apiprotocol__request_query__field_descriptors[4] =
{
  {
    "pathing",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__RequestQuery, n_pathing),
    offsetof(SC2APIProtocol__RequestQuery, pathing),
    &sc2_apiprotocol__request_query_pathing__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "abilities",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__RequestQuery, n_abilities),
    offsetof(SC2APIProtocol__RequestQuery, abilities),
    &sc2_apiprotocol__request_query_available_abilities__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "placements",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__RequestQuery, n_placements),
    offsetof(SC2APIProtocol__RequestQuery, placements),
    &sc2_apiprotocol__request_query_building_placement__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ignore_resource_requirements",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(SC2APIProtocol__RequestQuery, has_ignore_resource_requirements),
    offsetof(SC2APIProtocol__RequestQuery, ignore_resource_requirements),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__request_query__field_indices_by_name[] = {
  1,   /* field[1] = abilities */
  3,   /* field[3] = ignore_resource_requirements */
  0,   /* field[0] = pathing */
  2,   /* field[2] = placements */
};
static const ProtobufCIntRange sc2_apiprotocol__request_query__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__request_query__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.RequestQuery",
  "RequestQuery",
  "SC2APIProtocol__RequestQuery",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__RequestQuery),
  4,
  sc2_apiprotocol__request_query__field_descriptors,
  sc2_apiprotocol__request_query__field_indices_by_name,
  1,  sc2_apiprotocol__request_query__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__request_query__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__response_query__field_descriptors[3] =
{
  {
    "pathing",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__ResponseQuery, n_pathing),
    offsetof(SC2APIProtocol__ResponseQuery, pathing),
    &sc2_apiprotocol__response_query_pathing__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "abilities",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__ResponseQuery, n_abilities),
    offsetof(SC2APIProtocol__ResponseQuery, abilities),
    &sc2_apiprotocol__response_query_available_abilities__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "placements",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__ResponseQuery, n_placements),
    offsetof(SC2APIProtocol__ResponseQuery, placements),
    &sc2_apiprotocol__response_query_building_placement__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__response_query__field_indices_by_name[] = {
  1,   /* field[1] = abilities */
  0,   /* field[0] = pathing */
  2,   /* field[2] = placements */
};
static const ProtobufCIntRange sc2_apiprotocol__response_query__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__response_query__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.ResponseQuery",
  "ResponseQuery",
  "SC2APIProtocol__ResponseQuery",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__ResponseQuery),
  3,
  sc2_apiprotocol__response_query__field_descriptors,
  sc2_apiprotocol__response_query__field_indices_by_name,
  1,  sc2_apiprotocol__response_query__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__response_query__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__request_query_pathing__field_descriptors[3] =
{
  {
    "start_pos",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__RequestQueryPathing, start_case),
    offsetof(SC2APIProtocol__RequestQueryPathing, start_pos),
    &sc2_apiprotocol__point2_d__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unit_tag",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(SC2APIProtocol__RequestQueryPathing, start_case),
    offsetof(SC2APIProtocol__RequestQueryPathing, unit_tag),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end_pos",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__RequestQueryPathing, end_pos),
    &sc2_apiprotocol__point2_d__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__request_query_pathing__field_indices_by_name[] = {
  2,   /* field[2] = end_pos */
  0,   /* field[0] = start_pos */
  1,   /* field[1] = unit_tag */
};
static const ProtobufCIntRange sc2_apiprotocol__request_query_pathing__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__request_query_pathing__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.RequestQueryPathing",
  "RequestQueryPathing",
  "SC2APIProtocol__RequestQueryPathing",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__RequestQueryPathing),
  3,
  sc2_apiprotocol__request_query_pathing__field_descriptors,
  sc2_apiprotocol__request_query_pathing__field_indices_by_name,
  1,  sc2_apiprotocol__request_query_pathing__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__request_query_pathing__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__response_query_pathing__field_descriptors[1] =
{
  {
    "distance",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__ResponseQueryPathing, has_distance),
    offsetof(SC2APIProtocol__ResponseQueryPathing, distance),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__response_query_pathing__field_indices_by_name[] = {
  0,   /* field[0] = distance */
};
static const ProtobufCIntRange sc2_apiprotocol__response_query_pathing__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__response_query_pathing__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.ResponseQueryPathing",
  "ResponseQueryPathing",
  "SC2APIProtocol__ResponseQueryPathing",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__ResponseQueryPathing),
  1,
  sc2_apiprotocol__response_query_pathing__field_descriptors,
  sc2_apiprotocol__response_query_pathing__field_indices_by_name,
  1,  sc2_apiprotocol__response_query_pathing__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__response_query_pathing__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__request_query_available_abilities__field_descriptors[1] =
{
  {
    "unit_tag",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(SC2APIProtocol__RequestQueryAvailableAbilities, has_unit_tag),
    offsetof(SC2APIProtocol__RequestQueryAvailableAbilities, unit_tag),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__request_query_available_abilities__field_indices_by_name[] = {
  0,   /* field[0] = unit_tag */
};
static const ProtobufCIntRange sc2_apiprotocol__request_query_available_abilities__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__request_query_available_abilities__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.RequestQueryAvailableAbilities",
  "RequestQueryAvailableAbilities",
  "SC2APIProtocol__RequestQueryAvailableAbilities",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__RequestQueryAvailableAbilities),
  1,
  sc2_apiprotocol__request_query_available_abilities__field_descriptors,
  sc2_apiprotocol__request_query_available_abilities__field_indices_by_name,
  1,  sc2_apiprotocol__request_query_available_abilities__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__request_query_available_abilities__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__response_query_available_abilities__field_descriptors[3] =
{
  {
    "abilities",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__ResponseQueryAvailableAbilities, n_abilities),
    offsetof(SC2APIProtocol__ResponseQueryAvailableAbilities, abilities),
    &sc2_apiprotocol__available_ability__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unit_tag",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(SC2APIProtocol__ResponseQueryAvailableAbilities, has_unit_tag),
    offsetof(SC2APIProtocol__ResponseQueryAvailableAbilities, unit_tag),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unit_type_id",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SC2APIProtocol__ResponseQueryAvailableAbilities, has_unit_type_id),
    offsetof(SC2APIProtocol__ResponseQueryAvailableAbilities, unit_type_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__response_query_available_abilities__field_indices_by_name[] = {
  0,   /* field[0] = abilities */
  1,   /* field[1] = unit_tag */
  2,   /* field[2] = unit_type_id */
};
static const ProtobufCIntRange sc2_apiprotocol__response_query_available_abilities__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__response_query_available_abilities__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.ResponseQueryAvailableAbilities",
  "ResponseQueryAvailableAbilities",
  "SC2APIProtocol__ResponseQueryAvailableAbilities",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__ResponseQueryAvailableAbilities),
  3,
  sc2_apiprotocol__response_query_available_abilities__field_descriptors,
  sc2_apiprotocol__response_query_available_abilities__field_indices_by_name,
  1,  sc2_apiprotocol__response_query_available_abilities__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__response_query_available_abilities__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__request_query_building_placement__field_descriptors[3] =
{
  {
    "ability_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SC2APIProtocol__RequestQueryBuildingPlacement, has_ability_id),
    offsetof(SC2APIProtocol__RequestQueryBuildingPlacement, ability_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "target_pos",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__RequestQueryBuildingPlacement, target_pos),
    &sc2_apiprotocol__point2_d__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "placing_unit_tag",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(SC2APIProtocol__RequestQueryBuildingPlacement, has_placing_unit_tag),
    offsetof(SC2APIProtocol__RequestQueryBuildingPlacement, placing_unit_tag),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__request_query_building_placement__field_indices_by_name[] = {
  0,   /* field[0] = ability_id */
  2,   /* field[2] = placing_unit_tag */
  1,   /* field[1] = target_pos */
};
static const ProtobufCIntRange sc2_apiprotocol__request_query_building_placement__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__request_query_building_placement__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.RequestQueryBuildingPlacement",
  "RequestQueryBuildingPlacement",
  "SC2APIProtocol__RequestQueryBuildingPlacement",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__RequestQueryBuildingPlacement),
  3,
  sc2_apiprotocol__request_query_building_placement__field_descriptors,
  sc2_apiprotocol__request_query_building_placement__field_indices_by_name,
  1,  sc2_apiprotocol__request_query_building_placement__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__request_query_building_placement__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__response_query_building_placement__field_descriptors[1] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(SC2APIProtocol__ResponseQueryBuildingPlacement, has_result),
    offsetof(SC2APIProtocol__ResponseQueryBuildingPlacement, result),
    &sc2_apiprotocol__action_result__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__response_query_building_placement__field_indices_by_name[] = {
  0,   /* field[0] = result */
};
static const ProtobufCIntRange sc2_apiprotocol__response_query_building_placement__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__response_query_building_placement__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.ResponseQueryBuildingPlacement",
  "ResponseQueryBuildingPlacement",
  "SC2APIProtocol__ResponseQueryBuildingPlacement",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__ResponseQueryBuildingPlacement),
  1,
  sc2_apiprotocol__response_query_building_placement__field_descriptors,
  sc2_apiprotocol__response_query_building_placement__field_indices_by_name,
  1,  sc2_apiprotocol__response_query_building_placement__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__response_query_building_placement__init,
  NULL,NULL,NULL    /* reserved[123] */
};
