/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: s2clientprotocol/raw.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "s2clientprotocol/raw.pb-c.h"
void   sc2_apiprotocol__start_raw__init
                     (SC2APIProtocol__StartRaw         *message)
{
  static const SC2APIProtocol__StartRaw init_value = SC2_APIPROTOCOL__START_RAW__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__start_raw__get_packed_size
                     (const SC2APIProtocol__StartRaw *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__start_raw__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__start_raw__pack
                     (const SC2APIProtocol__StartRaw *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__start_raw__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__start_raw__pack_to_buffer
                     (const SC2APIProtocol__StartRaw *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__start_raw__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__StartRaw *
       sc2_apiprotocol__start_raw__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__StartRaw *)
     protobuf_c_message_unpack (&sc2_apiprotocol__start_raw__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__start_raw__free_unpacked
                     (SC2APIProtocol__StartRaw *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__start_raw__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__observation_raw__init
                     (SC2APIProtocol__ObservationRaw         *message)
{
  static const SC2APIProtocol__ObservationRaw init_value = SC2_APIPROTOCOL__OBSERVATION_RAW__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__observation_raw__get_packed_size
                     (const SC2APIProtocol__ObservationRaw *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__observation_raw__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__observation_raw__pack
                     (const SC2APIProtocol__ObservationRaw *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__observation_raw__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__observation_raw__pack_to_buffer
                     (const SC2APIProtocol__ObservationRaw *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__observation_raw__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__ObservationRaw *
       sc2_apiprotocol__observation_raw__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__ObservationRaw *)
     protobuf_c_message_unpack (&sc2_apiprotocol__observation_raw__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__observation_raw__free_unpacked
                     (SC2APIProtocol__ObservationRaw *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__observation_raw__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__radar_ring__init
                     (SC2APIProtocol__RadarRing         *message)
{
  static const SC2APIProtocol__RadarRing init_value = SC2_APIPROTOCOL__RADAR_RING__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__radar_ring__get_packed_size
                     (const SC2APIProtocol__RadarRing *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__radar_ring__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__radar_ring__pack
                     (const SC2APIProtocol__RadarRing *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__radar_ring__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__radar_ring__pack_to_buffer
                     (const SC2APIProtocol__RadarRing *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__radar_ring__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__RadarRing *
       sc2_apiprotocol__radar_ring__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__RadarRing *)
     protobuf_c_message_unpack (&sc2_apiprotocol__radar_ring__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__radar_ring__free_unpacked
                     (SC2APIProtocol__RadarRing *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__radar_ring__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__power_source__init
                     (SC2APIProtocol__PowerSource         *message)
{
  static const SC2APIProtocol__PowerSource init_value = SC2_APIPROTOCOL__POWER_SOURCE__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__power_source__get_packed_size
                     (const SC2APIProtocol__PowerSource *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__power_source__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__power_source__pack
                     (const SC2APIProtocol__PowerSource *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__power_source__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__power_source__pack_to_buffer
                     (const SC2APIProtocol__PowerSource *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__power_source__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__PowerSource *
       sc2_apiprotocol__power_source__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__PowerSource *)
     protobuf_c_message_unpack (&sc2_apiprotocol__power_source__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__power_source__free_unpacked
                     (SC2APIProtocol__PowerSource *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__power_source__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__player_raw__init
                     (SC2APIProtocol__PlayerRaw         *message)
{
  static const SC2APIProtocol__PlayerRaw init_value = SC2_APIPROTOCOL__PLAYER_RAW__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__player_raw__get_packed_size
                     (const SC2APIProtocol__PlayerRaw *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__player_raw__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__player_raw__pack
                     (const SC2APIProtocol__PlayerRaw *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__player_raw__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__player_raw__pack_to_buffer
                     (const SC2APIProtocol__PlayerRaw *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__player_raw__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__PlayerRaw *
       sc2_apiprotocol__player_raw__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__PlayerRaw *)
     protobuf_c_message_unpack (&sc2_apiprotocol__player_raw__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__player_raw__free_unpacked
                     (SC2APIProtocol__PlayerRaw *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__player_raw__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__unit_order__init
                     (SC2APIProtocol__UnitOrder         *message)
{
  static const SC2APIProtocol__UnitOrder init_value = SC2_APIPROTOCOL__UNIT_ORDER__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__unit_order__get_packed_size
                     (const SC2APIProtocol__UnitOrder *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__unit_order__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__unit_order__pack
                     (const SC2APIProtocol__UnitOrder *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__unit_order__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__unit_order__pack_to_buffer
                     (const SC2APIProtocol__UnitOrder *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__unit_order__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__UnitOrder *
       sc2_apiprotocol__unit_order__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__UnitOrder *)
     protobuf_c_message_unpack (&sc2_apiprotocol__unit_order__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__unit_order__free_unpacked
                     (SC2APIProtocol__UnitOrder *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__unit_order__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__passenger_unit__init
                     (SC2APIProtocol__PassengerUnit         *message)
{
  static const SC2APIProtocol__PassengerUnit init_value = SC2_APIPROTOCOL__PASSENGER_UNIT__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__passenger_unit__get_packed_size
                     (const SC2APIProtocol__PassengerUnit *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__passenger_unit__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__passenger_unit__pack
                     (const SC2APIProtocol__PassengerUnit *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__passenger_unit__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__passenger_unit__pack_to_buffer
                     (const SC2APIProtocol__PassengerUnit *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__passenger_unit__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__PassengerUnit *
       sc2_apiprotocol__passenger_unit__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__PassengerUnit *)
     protobuf_c_message_unpack (&sc2_apiprotocol__passenger_unit__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__passenger_unit__free_unpacked
                     (SC2APIProtocol__PassengerUnit *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__passenger_unit__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__rally_target__init
                     (SC2APIProtocol__RallyTarget         *message)
{
  static const SC2APIProtocol__RallyTarget init_value = SC2_APIPROTOCOL__RALLY_TARGET__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__rally_target__get_packed_size
                     (const SC2APIProtocol__RallyTarget *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__rally_target__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__rally_target__pack
                     (const SC2APIProtocol__RallyTarget *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__rally_target__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__rally_target__pack_to_buffer
                     (const SC2APIProtocol__RallyTarget *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__rally_target__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__RallyTarget *
       sc2_apiprotocol__rally_target__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__RallyTarget *)
     protobuf_c_message_unpack (&sc2_apiprotocol__rally_target__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__rally_target__free_unpacked
                     (SC2APIProtocol__RallyTarget *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__rally_target__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__unit__init
                     (SC2APIProtocol__Unit         *message)
{
  static const SC2APIProtocol__Unit init_value = SC2_APIPROTOCOL__UNIT__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__unit__get_packed_size
                     (const SC2APIProtocol__Unit *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__unit__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__unit__pack
                     (const SC2APIProtocol__Unit *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__unit__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__unit__pack_to_buffer
                     (const SC2APIProtocol__Unit *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__unit__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__Unit *
       sc2_apiprotocol__unit__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__Unit *)
     protobuf_c_message_unpack (&sc2_apiprotocol__unit__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__unit__free_unpacked
                     (SC2APIProtocol__Unit *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__unit__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__map_state__init
                     (SC2APIProtocol__MapState         *message)
{
  static const SC2APIProtocol__MapState init_value = SC2_APIPROTOCOL__MAP_STATE__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__map_state__get_packed_size
                     (const SC2APIProtocol__MapState *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__map_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__map_state__pack
                     (const SC2APIProtocol__MapState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__map_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__map_state__pack_to_buffer
                     (const SC2APIProtocol__MapState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__map_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__MapState *
       sc2_apiprotocol__map_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__MapState *)
     protobuf_c_message_unpack (&sc2_apiprotocol__map_state__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__map_state__free_unpacked
                     (SC2APIProtocol__MapState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__map_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__event__init
                     (SC2APIProtocol__Event         *message)
{
  static const SC2APIProtocol__Event init_value = SC2_APIPROTOCOL__EVENT__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__event__get_packed_size
                     (const SC2APIProtocol__Event *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__event__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__event__pack
                     (const SC2APIProtocol__Event *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__event__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__event__pack_to_buffer
                     (const SC2APIProtocol__Event *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__event__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__Event *
       sc2_apiprotocol__event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__Event *)
     protobuf_c_message_unpack (&sc2_apiprotocol__event__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__event__free_unpacked
                     (SC2APIProtocol__Event *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__event__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__effect__init
                     (SC2APIProtocol__Effect         *message)
{
  static const SC2APIProtocol__Effect init_value = SC2_APIPROTOCOL__EFFECT__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__effect__get_packed_size
                     (const SC2APIProtocol__Effect *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__effect__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__effect__pack
                     (const SC2APIProtocol__Effect *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__effect__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__effect__pack_to_buffer
                     (const SC2APIProtocol__Effect *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__effect__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__Effect *
       sc2_apiprotocol__effect__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__Effect *)
     protobuf_c_message_unpack (&sc2_apiprotocol__effect__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__effect__free_unpacked
                     (SC2APIProtocol__Effect *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__effect__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__action_raw__init
                     (SC2APIProtocol__ActionRaw         *message)
{
  static const SC2APIProtocol__ActionRaw init_value = SC2_APIPROTOCOL__ACTION_RAW__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__action_raw__get_packed_size
                     (const SC2APIProtocol__ActionRaw *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_raw__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__action_raw__pack
                     (const SC2APIProtocol__ActionRaw *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_raw__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__action_raw__pack_to_buffer
                     (const SC2APIProtocol__ActionRaw *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_raw__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__ActionRaw *
       sc2_apiprotocol__action_raw__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__ActionRaw *)
     protobuf_c_message_unpack (&sc2_apiprotocol__action_raw__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__action_raw__free_unpacked
                     (SC2APIProtocol__ActionRaw *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__action_raw__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__action_raw_unit_command__init
                     (SC2APIProtocol__ActionRawUnitCommand         *message)
{
  static const SC2APIProtocol__ActionRawUnitCommand init_value = SC2_APIPROTOCOL__ACTION_RAW_UNIT_COMMAND__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__action_raw_unit_command__get_packed_size
                     (const SC2APIProtocol__ActionRawUnitCommand *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_raw_unit_command__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__action_raw_unit_command__pack
                     (const SC2APIProtocol__ActionRawUnitCommand *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_raw_unit_command__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__action_raw_unit_command__pack_to_buffer
                     (const SC2APIProtocol__ActionRawUnitCommand *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_raw_unit_command__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__ActionRawUnitCommand *
       sc2_apiprotocol__action_raw_unit_command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__ActionRawUnitCommand *)
     protobuf_c_message_unpack (&sc2_apiprotocol__action_raw_unit_command__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__action_raw_unit_command__free_unpacked
                     (SC2APIProtocol__ActionRawUnitCommand *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__action_raw_unit_command__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__action_raw_camera_move__init
                     (SC2APIProtocol__ActionRawCameraMove         *message)
{
  static const SC2APIProtocol__ActionRawCameraMove init_value = SC2_APIPROTOCOL__ACTION_RAW_CAMERA_MOVE__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__action_raw_camera_move__get_packed_size
                     (const SC2APIProtocol__ActionRawCameraMove *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_raw_camera_move__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__action_raw_camera_move__pack
                     (const SC2APIProtocol__ActionRawCameraMove *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_raw_camera_move__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__action_raw_camera_move__pack_to_buffer
                     (const SC2APIProtocol__ActionRawCameraMove *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_raw_camera_move__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__ActionRawCameraMove *
       sc2_apiprotocol__action_raw_camera_move__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__ActionRawCameraMove *)
     protobuf_c_message_unpack (&sc2_apiprotocol__action_raw_camera_move__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__action_raw_camera_move__free_unpacked
                     (SC2APIProtocol__ActionRawCameraMove *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__action_raw_camera_move__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__action_raw_toggle_autocast__init
                     (SC2APIProtocol__ActionRawToggleAutocast         *message)
{
  static const SC2APIProtocol__ActionRawToggleAutocast init_value = SC2_APIPROTOCOL__ACTION_RAW_TOGGLE_AUTOCAST__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__action_raw_toggle_autocast__get_packed_size
                     (const SC2APIProtocol__ActionRawToggleAutocast *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_raw_toggle_autocast__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__action_raw_toggle_autocast__pack
                     (const SC2APIProtocol__ActionRawToggleAutocast *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_raw_toggle_autocast__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__action_raw_toggle_autocast__pack_to_buffer
                     (const SC2APIProtocol__ActionRawToggleAutocast *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_raw_toggle_autocast__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__ActionRawToggleAutocast *
       sc2_apiprotocol__action_raw_toggle_autocast__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__ActionRawToggleAutocast *)
     protobuf_c_message_unpack (&sc2_apiprotocol__action_raw_toggle_autocast__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__action_raw_toggle_autocast__free_unpacked
                     (SC2APIProtocol__ActionRawToggleAutocast *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__action_raw_toggle_autocast__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor sc2_apiprotocol__start_raw__field_descriptors[6] =
{
  {
    "map_size",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__StartRaw, map_size),
    &sc2_apiprotocol__size2_di__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pathing_grid",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__StartRaw, pathing_grid),
    &sc2_apiprotocol__image_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "terrain_height",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__StartRaw, terrain_height),
    &sc2_apiprotocol__image_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "placement_grid",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__StartRaw, placement_grid),
    &sc2_apiprotocol__image_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "playable_area",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__StartRaw, playable_area),
    &sc2_apiprotocol__rectangle_i__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start_locations",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__StartRaw, n_start_locations),
    offsetof(SC2APIProtocol__StartRaw, start_locations),
    &sc2_apiprotocol__point2_d__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__start_raw__field_indices_by_name[] = {
  0,   /* field[0] = map_size */
  1,   /* field[1] = pathing_grid */
  3,   /* field[3] = placement_grid */
  4,   /* field[4] = playable_area */
  5,   /* field[5] = start_locations */
  2,   /* field[2] = terrain_height */
};
static const ProtobufCIntRange sc2_apiprotocol__start_raw__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__start_raw__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.StartRaw",
  "StartRaw",
  "SC2APIProtocol__StartRaw",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__StartRaw),
  6,
  sc2_apiprotocol__start_raw__field_descriptors,
  sc2_apiprotocol__start_raw__field_indices_by_name,
  1,  sc2_apiprotocol__start_raw__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__start_raw__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__observation_raw__field_descriptors[6] =
{
  {
    "player",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__ObservationRaw, player),
    &sc2_apiprotocol__player_raw__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "units",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__ObservationRaw, n_units),
    offsetof(SC2APIProtocol__ObservationRaw, units),
    &sc2_apiprotocol__unit__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "map_state",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__ObservationRaw, map_state),
    &sc2_apiprotocol__map_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "event",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__ObservationRaw, event),
    &sc2_apiprotocol__event__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "effects",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__ObservationRaw, n_effects),
    offsetof(SC2APIProtocol__ObservationRaw, effects),
    &sc2_apiprotocol__effect__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "radar",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__ObservationRaw, n_radar),
    offsetof(SC2APIProtocol__ObservationRaw, radar),
    &sc2_apiprotocol__radar_ring__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__observation_raw__field_indices_by_name[] = {
  4,   /* field[4] = effects */
  3,   /* field[3] = event */
  2,   /* field[2] = map_state */
  0,   /* field[0] = player */
  5,   /* field[5] = radar */
  1,   /* field[1] = units */
};
static const ProtobufCIntRange sc2_apiprotocol__observation_raw__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__observation_raw__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.ObservationRaw",
  "ObservationRaw",
  "SC2APIProtocol__ObservationRaw",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__ObservationRaw),
  6,
  sc2_apiprotocol__observation_raw__field_descriptors,
  sc2_apiprotocol__observation_raw__field_indices_by_name,
  1,  sc2_apiprotocol__observation_raw__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__observation_raw__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__radar_ring__field_descriptors[2] =
{
  {
    "pos",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__RadarRing, pos),
    &sc2_apiprotocol__point__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "radius",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__RadarRing, has_radius),
    offsetof(SC2APIProtocol__RadarRing, radius),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__radar_ring__field_indices_by_name[] = {
  0,   /* field[0] = pos */
  1,   /* field[1] = radius */
};
static const ProtobufCIntRange sc2_apiprotocol__radar_ring__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__radar_ring__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.RadarRing",
  "RadarRing",
  "SC2APIProtocol__RadarRing",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__RadarRing),
  2,
  sc2_apiprotocol__radar_ring__field_descriptors,
  sc2_apiprotocol__radar_ring__field_indices_by_name,
  1,  sc2_apiprotocol__radar_ring__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__radar_ring__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__power_source__field_descriptors[3] =
{
  {
    "pos",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__PowerSource, pos),
    &sc2_apiprotocol__point__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "radius",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__PowerSource, has_radius),
    offsetof(SC2APIProtocol__PowerSource, radius),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tag",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(SC2APIProtocol__PowerSource, has_tag),
    offsetof(SC2APIProtocol__PowerSource, tag),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__power_source__field_indices_by_name[] = {
  0,   /* field[0] = pos */
  1,   /* field[1] = radius */
  2,   /* field[2] = tag */
};
static const ProtobufCIntRange sc2_apiprotocol__power_source__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__power_source__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.PowerSource",
  "PowerSource",
  "SC2APIProtocol__PowerSource",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__PowerSource),
  3,
  sc2_apiprotocol__power_source__field_descriptors,
  sc2_apiprotocol__power_source__field_indices_by_name,
  1,  sc2_apiprotocol__power_source__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__power_source__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__player_raw__field_descriptors[3] =
{
  {
    "power_sources",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__PlayerRaw, n_power_sources),
    offsetof(SC2APIProtocol__PlayerRaw, power_sources),
    &sc2_apiprotocol__power_source__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "camera",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__PlayerRaw, camera),
    &sc2_apiprotocol__point__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "upgrade_ids",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SC2APIProtocol__PlayerRaw, n_upgrade_ids),
    offsetof(SC2APIProtocol__PlayerRaw, upgrade_ids),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__player_raw__field_indices_by_name[] = {
  1,   /* field[1] = camera */
  0,   /* field[0] = power_sources */
  2,   /* field[2] = upgrade_ids */
};
static const ProtobufCIntRange sc2_apiprotocol__player_raw__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__player_raw__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.PlayerRaw",
  "PlayerRaw",
  "SC2APIProtocol__PlayerRaw",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__PlayerRaw),
  3,
  sc2_apiprotocol__player_raw__field_descriptors,
  sc2_apiprotocol__player_raw__field_indices_by_name,
  1,  sc2_apiprotocol__player_raw__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__player_raw__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__unit_order__field_descriptors[4] =
{
  {
    "ability_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SC2APIProtocol__UnitOrder, has_ability_id),
    offsetof(SC2APIProtocol__UnitOrder, ability_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "target_world_space_pos",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__UnitOrder, target_case),
    offsetof(SC2APIProtocol__UnitOrder, target_world_space_pos),
    &sc2_apiprotocol__point__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "target_unit_tag",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(SC2APIProtocol__UnitOrder, target_case),
    offsetof(SC2APIProtocol__UnitOrder, target_unit_tag),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "progress",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__UnitOrder, has_progress),
    offsetof(SC2APIProtocol__UnitOrder, progress),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__unit_order__field_indices_by_name[] = {
  0,   /* field[0] = ability_id */
  3,   /* field[3] = progress */
  2,   /* field[2] = target_unit_tag */
  1,   /* field[1] = target_world_space_pos */
};
static const ProtobufCIntRange sc2_apiprotocol__unit_order__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__unit_order__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.UnitOrder",
  "UnitOrder",
  "SC2APIProtocol__UnitOrder",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__UnitOrder),
  4,
  sc2_apiprotocol__unit_order__field_descriptors,
  sc2_apiprotocol__unit_order__field_indices_by_name,
  1,  sc2_apiprotocol__unit_order__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__unit_order__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__passenger_unit__field_descriptors[8] =
{
  {
    "tag",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(SC2APIProtocol__PassengerUnit, has_tag),
    offsetof(SC2APIProtocol__PassengerUnit, tag),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "health",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__PassengerUnit, has_health),
    offsetof(SC2APIProtocol__PassengerUnit, health),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "health_max",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__PassengerUnit, has_health_max),
    offsetof(SC2APIProtocol__PassengerUnit, health_max),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "shield",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__PassengerUnit, has_shield),
    offsetof(SC2APIProtocol__PassengerUnit, shield),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "energy",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__PassengerUnit, has_energy),
    offsetof(SC2APIProtocol__PassengerUnit, energy),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unit_type",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SC2APIProtocol__PassengerUnit, has_unit_type),
    offsetof(SC2APIProtocol__PassengerUnit, unit_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "shield_max",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__PassengerUnit, has_shield_max),
    offsetof(SC2APIProtocol__PassengerUnit, shield_max),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "energy_max",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__PassengerUnit, has_energy_max),
    offsetof(SC2APIProtocol__PassengerUnit, energy_max),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__passenger_unit__field_indices_by_name[] = {
  4,   /* field[4] = energy */
  7,   /* field[7] = energy_max */
  1,   /* field[1] = health */
  2,   /* field[2] = health_max */
  3,   /* field[3] = shield */
  6,   /* field[6] = shield_max */
  0,   /* field[0] = tag */
  5,   /* field[5] = unit_type */
};
static const ProtobufCIntRange sc2_apiprotocol__passenger_unit__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__passenger_unit__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.PassengerUnit",
  "PassengerUnit",
  "SC2APIProtocol__PassengerUnit",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__PassengerUnit),
  8,
  sc2_apiprotocol__passenger_unit__field_descriptors,
  sc2_apiprotocol__passenger_unit__field_indices_by_name,
  1,  sc2_apiprotocol__passenger_unit__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__passenger_unit__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__rally_target__field_descriptors[2] =
{
  {
    "point",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__RallyTarget, point),
    &sc2_apiprotocol__point__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tag",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(SC2APIProtocol__RallyTarget, has_tag),
    offsetof(SC2APIProtocol__RallyTarget, tag),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__rally_target__field_indices_by_name[] = {
  0,   /* field[0] = point */
  1,   /* field[1] = tag */
};
static const ProtobufCIntRange sc2_apiprotocol__rally_target__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__rally_target__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.RallyTarget",
  "RallyTarget",
  "SC2APIProtocol__RallyTarget",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__RallyTarget),
  2,
  sc2_apiprotocol__rally_target__field_descriptors,
  sc2_apiprotocol__rally_target__field_indices_by_name,
  1,  sc2_apiprotocol__rally_target__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__rally_target__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__unit__field_descriptors[44] =
{
  {
    "display_type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(SC2APIProtocol__Unit, has_display_type),
    offsetof(SC2APIProtocol__Unit, display_type),
    &sc2_apiprotocol__display_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "alliance",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(SC2APIProtocol__Unit, has_alliance),
    offsetof(SC2APIProtocol__Unit, alliance),
    &sc2_apiprotocol__alliance__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tag",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(SC2APIProtocol__Unit, has_tag),
    offsetof(SC2APIProtocol__Unit, tag),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unit_type",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SC2APIProtocol__Unit, has_unit_type),
    offsetof(SC2APIProtocol__Unit, unit_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "owner",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SC2APIProtocol__Unit, has_owner),
    offsetof(SC2APIProtocol__Unit, owner),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__Unit, pos),
    &sc2_apiprotocol__point__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "facing",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__Unit, has_facing),
    offsetof(SC2APIProtocol__Unit, facing),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "radius",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__Unit, has_radius),
    offsetof(SC2APIProtocol__Unit, radius),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "build_progress",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__Unit, has_build_progress),
    offsetof(SC2APIProtocol__Unit, build_progress),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cloak",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(SC2APIProtocol__Unit, has_cloak),
    offsetof(SC2APIProtocol__Unit, cloak),
    &sc2_apiprotocol__cloak_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_selected",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(SC2APIProtocol__Unit, has_is_selected),
    offsetof(SC2APIProtocol__Unit, is_selected),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_on_screen",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(SC2APIProtocol__Unit, has_is_on_screen),
    offsetof(SC2APIProtocol__Unit, is_on_screen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_blip",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(SC2APIProtocol__Unit, has_is_blip),
    offsetof(SC2APIProtocol__Unit, is_blip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "health",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__Unit, has_health),
    offsetof(SC2APIProtocol__Unit, health),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "health_max",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__Unit, has_health_max),
    offsetof(SC2APIProtocol__Unit, health_max),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "shield",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__Unit, has_shield),
    offsetof(SC2APIProtocol__Unit, shield),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "energy",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__Unit, has_energy),
    offsetof(SC2APIProtocol__Unit, energy),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mineral_contents",
    18,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SC2APIProtocol__Unit, has_mineral_contents),
    offsetof(SC2APIProtocol__Unit, mineral_contents),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vespene_contents",
    19,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SC2APIProtocol__Unit, has_vespene_contents),
    offsetof(SC2APIProtocol__Unit, vespene_contents),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_flying",
    20,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(SC2APIProtocol__Unit, has_is_flying),
    offsetof(SC2APIProtocol__Unit, is_flying),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_burrowed",
    21,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(SC2APIProtocol__Unit, has_is_burrowed),
    offsetof(SC2APIProtocol__Unit, is_burrowed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "orders",
    22,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__Unit, n_orders),
    offsetof(SC2APIProtocol__Unit, orders),
    &sc2_apiprotocol__unit_order__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "add_on_tag",
    23,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(SC2APIProtocol__Unit, has_add_on_tag),
    offsetof(SC2APIProtocol__Unit, add_on_tag),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "passengers",
    24,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__Unit, n_passengers),
    offsetof(SC2APIProtocol__Unit, passengers),
    &sc2_apiprotocol__passenger_unit__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cargo_space_taken",
    25,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SC2APIProtocol__Unit, has_cargo_space_taken),
    offsetof(SC2APIProtocol__Unit, cargo_space_taken),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cargo_space_max",
    26,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SC2APIProtocol__Unit, has_cargo_space_max),
    offsetof(SC2APIProtocol__Unit, cargo_space_max),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "buff_ids",
    27,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SC2APIProtocol__Unit, n_buff_ids),
    offsetof(SC2APIProtocol__Unit, buff_ids),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "assigned_harvesters",
    28,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SC2APIProtocol__Unit, has_assigned_harvesters),
    offsetof(SC2APIProtocol__Unit, assigned_harvesters),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ideal_harvesters",
    29,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SC2APIProtocol__Unit, has_ideal_harvesters),
    offsetof(SC2APIProtocol__Unit, ideal_harvesters),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "weapon_cooldown",
    30,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__Unit, has_weapon_cooldown),
    offsetof(SC2APIProtocol__Unit, weapon_cooldown),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "detect_range",
    31,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__Unit, has_detect_range),
    offsetof(SC2APIProtocol__Unit, detect_range),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "radar_range",
    32,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__Unit, has_radar_range),
    offsetof(SC2APIProtocol__Unit, radar_range),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "engaged_target_tag",
    34,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(SC2APIProtocol__Unit, has_engaged_target_tag),
    offsetof(SC2APIProtocol__Unit, engaged_target_tag),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_powered",
    35,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(SC2APIProtocol__Unit, has_is_powered),
    offsetof(SC2APIProtocol__Unit, is_powered),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "shield_max",
    36,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__Unit, has_shield_max),
    offsetof(SC2APIProtocol__Unit, shield_max),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "energy_max",
    37,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__Unit, has_energy_max),
    offsetof(SC2APIProtocol__Unit, energy_max),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_hallucination",
    38,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(SC2APIProtocol__Unit, has_is_hallucination),
    offsetof(SC2APIProtocol__Unit, is_hallucination),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_active",
    39,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(SC2APIProtocol__Unit, has_is_active),
    offsetof(SC2APIProtocol__Unit, is_active),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attack_upgrade_level",
    40,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SC2APIProtocol__Unit, has_attack_upgrade_level),
    offsetof(SC2APIProtocol__Unit, attack_upgrade_level),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "armor_upgrade_level",
    41,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SC2APIProtocol__Unit, has_armor_upgrade_level),
    offsetof(SC2APIProtocol__Unit, armor_upgrade_level),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "shield_upgrade_level",
    42,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SC2APIProtocol__Unit, has_shield_upgrade_level),
    offsetof(SC2APIProtocol__Unit, shield_upgrade_level),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "buff_duration_remain",
    43,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SC2APIProtocol__Unit, has_buff_duration_remain),
    offsetof(SC2APIProtocol__Unit, buff_duration_remain),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "buff_duration_max",
    44,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SC2APIProtocol__Unit, has_buff_duration_max),
    offsetof(SC2APIProtocol__Unit, buff_duration_max),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rally_targets",
    45,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__Unit, n_rally_targets),
    offsetof(SC2APIProtocol__Unit, rally_targets),
    &sc2_apiprotocol__rally_target__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__unit__field_indices_by_name[] = {
  22,   /* field[22] = add_on_tag */
  1,   /* field[1] = alliance */
  39,   /* field[39] = armor_upgrade_level */
  27,   /* field[27] = assigned_harvesters */
  38,   /* field[38] = attack_upgrade_level */
  42,   /* field[42] = buff_duration_max */
  41,   /* field[41] = buff_duration_remain */
  26,   /* field[26] = buff_ids */
  8,   /* field[8] = build_progress */
  25,   /* field[25] = cargo_space_max */
  24,   /* field[24] = cargo_space_taken */
  9,   /* field[9] = cloak */
  30,   /* field[30] = detect_range */
  0,   /* field[0] = display_type */
  16,   /* field[16] = energy */
  35,   /* field[35] = energy_max */
  32,   /* field[32] = engaged_target_tag */
  6,   /* field[6] = facing */
  13,   /* field[13] = health */
  14,   /* field[14] = health_max */
  28,   /* field[28] = ideal_harvesters */
  37,   /* field[37] = is_active */
  12,   /* field[12] = is_blip */
  20,   /* field[20] = is_burrowed */
  19,   /* field[19] = is_flying */
  36,   /* field[36] = is_hallucination */
  11,   /* field[11] = is_on_screen */
  33,   /* field[33] = is_powered */
  10,   /* field[10] = is_selected */
  17,   /* field[17] = mineral_contents */
  21,   /* field[21] = orders */
  4,   /* field[4] = owner */
  23,   /* field[23] = passengers */
  5,   /* field[5] = pos */
  31,   /* field[31] = radar_range */
  7,   /* field[7] = radius */
  43,   /* field[43] = rally_targets */
  15,   /* field[15] = shield */
  34,   /* field[34] = shield_max */
  40,   /* field[40] = shield_upgrade_level */
  2,   /* field[2] = tag */
  3,   /* field[3] = unit_type */
  18,   /* field[18] = vespene_contents */
  29,   /* field[29] = weapon_cooldown */
};
static const ProtobufCIntRange sc2_apiprotocol__unit__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 34, 32 },
  { 0, 44 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__unit__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.Unit",
  "Unit",
  "SC2APIProtocol__Unit",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__Unit),
  44,
  sc2_apiprotocol__unit__field_descriptors,
  sc2_apiprotocol__unit__field_indices_by_name,
  2,  sc2_apiprotocol__unit__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__unit__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__map_state__field_descriptors[2] =
{
  {
    "visibility",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__MapState, visibility),
    &sc2_apiprotocol__image_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "creep",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__MapState, creep),
    &sc2_apiprotocol__image_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__map_state__field_indices_by_name[] = {
  1,   /* field[1] = creep */
  0,   /* field[0] = visibility */
};
static const ProtobufCIntRange sc2_apiprotocol__map_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__map_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.MapState",
  "MapState",
  "SC2APIProtocol__MapState",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__MapState),
  2,
  sc2_apiprotocol__map_state__field_descriptors,
  sc2_apiprotocol__map_state__field_indices_by_name,
  1,  sc2_apiprotocol__map_state__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__map_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__event__field_descriptors[1] =
{
  {
    "dead_units",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(SC2APIProtocol__Event, n_dead_units),
    offsetof(SC2APIProtocol__Event, dead_units),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__event__field_indices_by_name[] = {
  0,   /* field[0] = dead_units */
};
static const ProtobufCIntRange sc2_apiprotocol__event__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__event__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.Event",
  "Event",
  "SC2APIProtocol__Event",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__Event),
  1,
  sc2_apiprotocol__event__field_descriptors,
  sc2_apiprotocol__event__field_indices_by_name,
  1,  sc2_apiprotocol__event__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__event__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__effect__field_descriptors[5] =
{
  {
    "effect_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SC2APIProtocol__Effect, has_effect_id),
    offsetof(SC2APIProtocol__Effect, effect_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__Effect, n_pos),
    offsetof(SC2APIProtocol__Effect, pos),
    &sc2_apiprotocol__point2_d__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "alliance",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(SC2APIProtocol__Effect, has_alliance),
    offsetof(SC2APIProtocol__Effect, alliance),
    &sc2_apiprotocol__alliance__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "owner",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SC2APIProtocol__Effect, has_owner),
    offsetof(SC2APIProtocol__Effect, owner),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "radius",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__Effect, has_radius),
    offsetof(SC2APIProtocol__Effect, radius),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__effect__field_indices_by_name[] = {
  2,   /* field[2] = alliance */
  0,   /* field[0] = effect_id */
  3,   /* field[3] = owner */
  1,   /* field[1] = pos */
  4,   /* field[4] = radius */
};
static const ProtobufCIntRange sc2_apiprotocol__effect__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__effect__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.Effect",
  "Effect",
  "SC2APIProtocol__Effect",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__Effect),
  5,
  sc2_apiprotocol__effect__field_descriptors,
  sc2_apiprotocol__effect__field_indices_by_name,
  1,  sc2_apiprotocol__effect__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__effect__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__action_raw__field_descriptors[3] =
{
  {
    "unit_command",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__ActionRaw, action_case),
    offsetof(SC2APIProtocol__ActionRaw, unit_command),
    &sc2_apiprotocol__action_raw_unit_command__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "camera_move",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__ActionRaw, action_case),
    offsetof(SC2APIProtocol__ActionRaw, camera_move),
    &sc2_apiprotocol__action_raw_camera_move__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "toggle_autocast",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__ActionRaw, action_case),
    offsetof(SC2APIProtocol__ActionRaw, toggle_autocast),
    &sc2_apiprotocol__action_raw_toggle_autocast__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__action_raw__field_indices_by_name[] = {
  1,   /* field[1] = camera_move */
  2,   /* field[2] = toggle_autocast */
  0,   /* field[0] = unit_command */
};
static const ProtobufCIntRange sc2_apiprotocol__action_raw__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__action_raw__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.ActionRaw",
  "ActionRaw",
  "SC2APIProtocol__ActionRaw",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__ActionRaw),
  3,
  sc2_apiprotocol__action_raw__field_descriptors,
  sc2_apiprotocol__action_raw__field_indices_by_name,
  1,  sc2_apiprotocol__action_raw__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__action_raw__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__action_raw_unit_command__field_descriptors[5] =
{
  {
    "ability_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SC2APIProtocol__ActionRawUnitCommand, has_ability_id),
    offsetof(SC2APIProtocol__ActionRawUnitCommand, ability_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "target_world_space_pos",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__ActionRawUnitCommand, target_case),
    offsetof(SC2APIProtocol__ActionRawUnitCommand, target_world_space_pos),
    &sc2_apiprotocol__point2_d__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "target_unit_tag",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(SC2APIProtocol__ActionRawUnitCommand, target_case),
    offsetof(SC2APIProtocol__ActionRawUnitCommand, target_unit_tag),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unit_tags",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(SC2APIProtocol__ActionRawUnitCommand, n_unit_tags),
    offsetof(SC2APIProtocol__ActionRawUnitCommand, unit_tags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "queue_command",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(SC2APIProtocol__ActionRawUnitCommand, has_queue_command),
    offsetof(SC2APIProtocol__ActionRawUnitCommand, queue_command),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__action_raw_unit_command__field_indices_by_name[] = {
  0,   /* field[0] = ability_id */
  4,   /* field[4] = queue_command */
  2,   /* field[2] = target_unit_tag */
  1,   /* field[1] = target_world_space_pos */
  3,   /* field[3] = unit_tags */
};
static const ProtobufCIntRange sc2_apiprotocol__action_raw_unit_command__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__action_raw_unit_command__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.ActionRawUnitCommand",
  "ActionRawUnitCommand",
  "SC2APIProtocol__ActionRawUnitCommand",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__ActionRawUnitCommand),
  5,
  sc2_apiprotocol__action_raw_unit_command__field_descriptors,
  sc2_apiprotocol__action_raw_unit_command__field_indices_by_name,
  1,  sc2_apiprotocol__action_raw_unit_command__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__action_raw_unit_command__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__action_raw_camera_move__field_descriptors[1] =
{
  {
    "center_world_space",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__ActionRawCameraMove, center_world_space),
    &sc2_apiprotocol__point__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__action_raw_camera_move__field_indices_by_name[] = {
  0,   /* field[0] = center_world_space */
};
static const ProtobufCIntRange sc2_apiprotocol__action_raw_camera_move__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__action_raw_camera_move__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.ActionRawCameraMove",
  "ActionRawCameraMove",
  "SC2APIProtocol__ActionRawCameraMove",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__ActionRawCameraMove),
  1,
  sc2_apiprotocol__action_raw_camera_move__field_descriptors,
  sc2_apiprotocol__action_raw_camera_move__field_indices_by_name,
  1,  sc2_apiprotocol__action_raw_camera_move__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__action_raw_camera_move__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__action_raw_toggle_autocast__field_descriptors[2] =
{
  {
    "ability_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SC2APIProtocol__ActionRawToggleAutocast, has_ability_id),
    offsetof(SC2APIProtocol__ActionRawToggleAutocast, ability_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unit_tags",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(SC2APIProtocol__ActionRawToggleAutocast, n_unit_tags),
    offsetof(SC2APIProtocol__ActionRawToggleAutocast, unit_tags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__action_raw_toggle_autocast__field_indices_by_name[] = {
  0,   /* field[0] = ability_id */
  1,   /* field[1] = unit_tags */
};
static const ProtobufCIntRange sc2_apiprotocol__action_raw_toggle_autocast__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__action_raw_toggle_autocast__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.ActionRawToggleAutocast",
  "ActionRawToggleAutocast",
  "SC2APIProtocol__ActionRawToggleAutocast",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__ActionRawToggleAutocast),
  2,
  sc2_apiprotocol__action_raw_toggle_autocast__field_descriptors,
  sc2_apiprotocol__action_raw_toggle_autocast__field_indices_by_name,
  1,  sc2_apiprotocol__action_raw_toggle_autocast__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__action_raw_toggle_autocast__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue sc2_apiprotocol__display_type__enum_values_by_number[4] =
{
  { "Visible", "SC2_APIPROTOCOL__DISPLAY_TYPE__Visible", 1 },
  { "Snapshot", "SC2_APIPROTOCOL__DISPLAY_TYPE__Snapshot", 2 },
  { "Hidden", "SC2_APIPROTOCOL__DISPLAY_TYPE__Hidden", 3 },
  { "Placeholder", "SC2_APIPROTOCOL__DISPLAY_TYPE__Placeholder", 4 },
};
static const ProtobufCIntRange sc2_apiprotocol__display_type__value_ranges[] = {
{1, 0},{0, 4}
};
static const ProtobufCEnumValueIndex sc2_apiprotocol__display_type__enum_values_by_name[4] =
{
  { "Hidden", 2 },
  { "Placeholder", 3 },
  { "Snapshot", 1 },
  { "Visible", 0 },
};
const ProtobufCEnumDescriptor sc2_apiprotocol__display_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.DisplayType",
  "DisplayType",
  "SC2APIProtocol__DisplayType",
  "SC2APIProtocol",
  4,
  sc2_apiprotocol__display_type__enum_values_by_number,
  4,
  sc2_apiprotocol__display_type__enum_values_by_name,
  1,
  sc2_apiprotocol__display_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue sc2_apiprotocol__alliance__enum_values_by_number[4] =
{
  { "Self", "SC2_APIPROTOCOL__ALLIANCE__Self", 1 },
  { "Ally", "SC2_APIPROTOCOL__ALLIANCE__Ally", 2 },
  { "Neutral", "SC2_APIPROTOCOL__ALLIANCE__Neutral", 3 },
  { "Enemy", "SC2_APIPROTOCOL__ALLIANCE__Enemy", 4 },
};
static const ProtobufCIntRange sc2_apiprotocol__alliance__value_ranges[] = {
{1, 0},{0, 4}
};
static const ProtobufCEnumValueIndex sc2_apiprotocol__alliance__enum_values_by_name[4] =
{
  { "Ally", 1 },
  { "Enemy", 3 },
  { "Neutral", 2 },
  { "Self", 0 },
};
const ProtobufCEnumDescriptor sc2_apiprotocol__alliance__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.Alliance",
  "Alliance",
  "SC2APIProtocol__Alliance",
  "SC2APIProtocol",
  4,
  sc2_apiprotocol__alliance__enum_values_by_number,
  4,
  sc2_apiprotocol__alliance__enum_values_by_name,
  1,
  sc2_apiprotocol__alliance__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue sc2_apiprotocol__cloak_state__enum_values_by_number[5] =
{
  { "CloakedUnknown", "SC2_APIPROTOCOL__CLOAK_STATE__CloakedUnknown", 0 },
  { "Cloaked", "SC2_APIPROTOCOL__CLOAK_STATE__Cloaked", 1 },
  { "CloakedDetected", "SC2_APIPROTOCOL__CLOAK_STATE__CloakedDetected", 2 },
  { "NotCloaked", "SC2_APIPROTOCOL__CLOAK_STATE__NotCloaked", 3 },
  { "CloakedAllied", "SC2_APIPROTOCOL__CLOAK_STATE__CloakedAllied", 4 },
};
static const ProtobufCIntRange sc2_apiprotocol__cloak_state__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex sc2_apiprotocol__cloak_state__enum_values_by_name[5] =
{
  { "Cloaked", 1 },
  { "CloakedAllied", 4 },
  { "CloakedDetected", 2 },
  { "CloakedUnknown", 0 },
  { "NotCloaked", 3 },
};
const ProtobufCEnumDescriptor sc2_apiprotocol__cloak_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.CloakState",
  "CloakState",
  "SC2APIProtocol__CloakState",
  "SC2APIProtocol",
  5,
  sc2_apiprotocol__cloak_state__enum_values_by_number,
  5,
  sc2_apiprotocol__cloak_state__enum_values_by_name,
  1,
  sc2_apiprotocol__cloak_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
