/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: s2clientprotocol/score.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "s2clientprotocol/score.pb-c.h"
void   sc2_apiprotocol__score__init
                     (SC2APIProtocol__Score         *message)
{
  static const SC2APIProtocol__Score init_value = SC2_APIPROTOCOL__SCORE__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__score__get_packed_size
                     (const SC2APIProtocol__Score *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__score__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__score__pack
                     (const SC2APIProtocol__Score *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__score__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__score__pack_to_buffer
                     (const SC2APIProtocol__Score *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__score__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__Score *
       sc2_apiprotocol__score__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__Score *)
     protobuf_c_message_unpack (&sc2_apiprotocol__score__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__score__free_unpacked
                     (SC2APIProtocol__Score *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__score__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__category_score_details__init
                     (SC2APIProtocol__CategoryScoreDetails         *message)
{
  static const SC2APIProtocol__CategoryScoreDetails init_value = SC2_APIPROTOCOL__CATEGORY_SCORE_DETAILS__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__category_score_details__get_packed_size
                     (const SC2APIProtocol__CategoryScoreDetails *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__category_score_details__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__category_score_details__pack
                     (const SC2APIProtocol__CategoryScoreDetails *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__category_score_details__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__category_score_details__pack_to_buffer
                     (const SC2APIProtocol__CategoryScoreDetails *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__category_score_details__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__CategoryScoreDetails *
       sc2_apiprotocol__category_score_details__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__CategoryScoreDetails *)
     protobuf_c_message_unpack (&sc2_apiprotocol__category_score_details__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__category_score_details__free_unpacked
                     (SC2APIProtocol__CategoryScoreDetails *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__category_score_details__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__vital_score_details__init
                     (SC2APIProtocol__VitalScoreDetails         *message)
{
  static const SC2APIProtocol__VitalScoreDetails init_value = SC2_APIPROTOCOL__VITAL_SCORE_DETAILS__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__vital_score_details__get_packed_size
                     (const SC2APIProtocol__VitalScoreDetails *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__vital_score_details__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__vital_score_details__pack
                     (const SC2APIProtocol__VitalScoreDetails *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__vital_score_details__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__vital_score_details__pack_to_buffer
                     (const SC2APIProtocol__VitalScoreDetails *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__vital_score_details__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__VitalScoreDetails *
       sc2_apiprotocol__vital_score_details__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__VitalScoreDetails *)
     protobuf_c_message_unpack (&sc2_apiprotocol__vital_score_details__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__vital_score_details__free_unpacked
                     (SC2APIProtocol__VitalScoreDetails *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__vital_score_details__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__score_details__init
                     (SC2APIProtocol__ScoreDetails         *message)
{
  static const SC2APIProtocol__ScoreDetails init_value = SC2_APIPROTOCOL__SCORE_DETAILS__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__score_details__get_packed_size
                     (const SC2APIProtocol__ScoreDetails *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__score_details__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__score_details__pack
                     (const SC2APIProtocol__ScoreDetails *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__score_details__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__score_details__pack_to_buffer
                     (const SC2APIProtocol__ScoreDetails *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__score_details__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__ScoreDetails *
       sc2_apiprotocol__score_details__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__ScoreDetails *)
     protobuf_c_message_unpack (&sc2_apiprotocol__score_details__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__score_details__free_unpacked
                     (SC2APIProtocol__ScoreDetails *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__score_details__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue sc2_apiprotocol__score__score_type__enum_values_by_number[2] =
{
  { "Curriculum", "SC2_APIPROTOCOL__SCORE__SCORE_TYPE__Curriculum", 1 },
  { "Melee", "SC2_APIPROTOCOL__SCORE__SCORE_TYPE__Melee", 2 },
};
static const ProtobufCIntRange sc2_apiprotocol__score__score_type__value_ranges[] = {
{1, 0},{0, 2}
};
static const ProtobufCEnumValueIndex sc2_apiprotocol__score__score_type__enum_values_by_name[2] =
{
  { "Curriculum", 0 },
  { "Melee", 1 },
};
const ProtobufCEnumDescriptor sc2_apiprotocol__score__score_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.Score.ScoreType",
  "ScoreType",
  "SC2APIProtocol__Score__ScoreType",
  "SC2APIProtocol",
  2,
  sc2_apiprotocol__score__score_type__enum_values_by_number,
  2,
  sc2_apiprotocol__score__score_type__enum_values_by_name,
  1,
  sc2_apiprotocol__score__score_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__score__field_descriptors[3] =
{
  {
    "score_type",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(SC2APIProtocol__Score, has_score_type),
    offsetof(SC2APIProtocol__Score, score_type),
    &sc2_apiprotocol__score__score_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "score",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SC2APIProtocol__Score, has_score),
    offsetof(SC2APIProtocol__Score, score),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "score_details",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__Score, score_details),
    &sc2_apiprotocol__score_details__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__score__field_indices_by_name[] = {
  1,   /* field[1] = score */
  2,   /* field[2] = score_details */
  0,   /* field[0] = score_type */
};
static const ProtobufCIntRange sc2_apiprotocol__score__number_ranges[1 + 1] =
{
  { 6, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__score__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.Score",
  "Score",
  "SC2APIProtocol__Score",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__Score),
  3,
  sc2_apiprotocol__score__field_descriptors,
  sc2_apiprotocol__score__field_indices_by_name,
  1,  sc2_apiprotocol__score__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__score__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__category_score_details__field_descriptors[5] =
{
  {
    "none",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__CategoryScoreDetails, has_none),
    offsetof(SC2APIProtocol__CategoryScoreDetails, none),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "army",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__CategoryScoreDetails, has_army),
    offsetof(SC2APIProtocol__CategoryScoreDetails, army),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "economy",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__CategoryScoreDetails, has_economy),
    offsetof(SC2APIProtocol__CategoryScoreDetails, economy),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "technology",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__CategoryScoreDetails, has_technology),
    offsetof(SC2APIProtocol__CategoryScoreDetails, technology),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "upgrade",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__CategoryScoreDetails, has_upgrade),
    offsetof(SC2APIProtocol__CategoryScoreDetails, upgrade),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__category_score_details__field_indices_by_name[] = {
  1,   /* field[1] = army */
  2,   /* field[2] = economy */
  0,   /* field[0] = none */
  3,   /* field[3] = technology */
  4,   /* field[4] = upgrade */
};
static const ProtobufCIntRange sc2_apiprotocol__category_score_details__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__category_score_details__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.CategoryScoreDetails",
  "CategoryScoreDetails",
  "SC2APIProtocol__CategoryScoreDetails",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__CategoryScoreDetails),
  5,
  sc2_apiprotocol__category_score_details__field_descriptors,
  sc2_apiprotocol__category_score_details__field_indices_by_name,
  1,  sc2_apiprotocol__category_score_details__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__category_score_details__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__vital_score_details__field_descriptors[3] =
{
  {
    "life",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__VitalScoreDetails, has_life),
    offsetof(SC2APIProtocol__VitalScoreDetails, life),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "shields",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__VitalScoreDetails, has_shields),
    offsetof(SC2APIProtocol__VitalScoreDetails, shields),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "energy",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__VitalScoreDetails, has_energy),
    offsetof(SC2APIProtocol__VitalScoreDetails, energy),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__vital_score_details__field_indices_by_name[] = {
  2,   /* field[2] = energy */
  0,   /* field[0] = life */
  1,   /* field[1] = shields */
};
static const ProtobufCIntRange sc2_apiprotocol__vital_score_details__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__vital_score_details__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.VitalScoreDetails",
  "VitalScoreDetails",
  "SC2APIProtocol__VitalScoreDetails",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__VitalScoreDetails),
  3,
  sc2_apiprotocol__vital_score_details__field_descriptors,
  sc2_apiprotocol__vital_score_details__field_indices_by_name,
  1,  sc2_apiprotocol__vital_score_details__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__vital_score_details__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__score_details__field_descriptors[28] =
{
  {
    "idle_production_time",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__ScoreDetails, has_idle_production_time),
    offsetof(SC2APIProtocol__ScoreDetails, idle_production_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "idle_worker_time",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__ScoreDetails, has_idle_worker_time),
    offsetof(SC2APIProtocol__ScoreDetails, idle_worker_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "total_value_units",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__ScoreDetails, has_total_value_units),
    offsetof(SC2APIProtocol__ScoreDetails, total_value_units),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "total_value_structures",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__ScoreDetails, has_total_value_structures),
    offsetof(SC2APIProtocol__ScoreDetails, total_value_structures),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "killed_value_units",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__ScoreDetails, has_killed_value_units),
    offsetof(SC2APIProtocol__ScoreDetails, killed_value_units),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "killed_value_structures",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__ScoreDetails, has_killed_value_structures),
    offsetof(SC2APIProtocol__ScoreDetails, killed_value_structures),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "collected_minerals",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__ScoreDetails, has_collected_minerals),
    offsetof(SC2APIProtocol__ScoreDetails, collected_minerals),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "collected_vespene",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__ScoreDetails, has_collected_vespene),
    offsetof(SC2APIProtocol__ScoreDetails, collected_vespene),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "collection_rate_minerals",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__ScoreDetails, has_collection_rate_minerals),
    offsetof(SC2APIProtocol__ScoreDetails, collection_rate_minerals),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "collection_rate_vespene",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__ScoreDetails, has_collection_rate_vespene),
    offsetof(SC2APIProtocol__ScoreDetails, collection_rate_vespene),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "spent_minerals",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__ScoreDetails, has_spent_minerals),
    offsetof(SC2APIProtocol__ScoreDetails, spent_minerals),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "spent_vespene",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__ScoreDetails, has_spent_vespene),
    offsetof(SC2APIProtocol__ScoreDetails, spent_vespene),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "food_used",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__ScoreDetails, food_used),
    &sc2_apiprotocol__category_score_details__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "killed_minerals",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__ScoreDetails, killed_minerals),
    &sc2_apiprotocol__category_score_details__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "killed_vespene",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__ScoreDetails, killed_vespene),
    &sc2_apiprotocol__category_score_details__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lost_minerals",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__ScoreDetails, lost_minerals),
    &sc2_apiprotocol__category_score_details__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lost_vespene",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__ScoreDetails, lost_vespene),
    &sc2_apiprotocol__category_score_details__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "friendly_fire_minerals",
    18,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__ScoreDetails, friendly_fire_minerals),
    &sc2_apiprotocol__category_score_details__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "friendly_fire_vespene",
    19,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__ScoreDetails, friendly_fire_vespene),
    &sc2_apiprotocol__category_score_details__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "used_minerals",
    20,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__ScoreDetails, used_minerals),
    &sc2_apiprotocol__category_score_details__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "used_vespene",
    21,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__ScoreDetails, used_vespene),
    &sc2_apiprotocol__category_score_details__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "total_used_minerals",
    22,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__ScoreDetails, total_used_minerals),
    &sc2_apiprotocol__category_score_details__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "total_used_vespene",
    23,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__ScoreDetails, total_used_vespene),
    &sc2_apiprotocol__category_score_details__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "total_damage_dealt",
    24,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__ScoreDetails, total_damage_dealt),
    &sc2_apiprotocol__vital_score_details__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "total_damage_taken",
    25,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__ScoreDetails, total_damage_taken),
    &sc2_apiprotocol__vital_score_details__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "total_healed",
    26,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__ScoreDetails, total_healed),
    &sc2_apiprotocol__vital_score_details__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current_apm",
    27,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__ScoreDetails, has_current_apm),
    offsetof(SC2APIProtocol__ScoreDetails, current_apm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current_effective_apm",
    28,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__ScoreDetails, has_current_effective_apm),
    offsetof(SC2APIProtocol__ScoreDetails, current_effective_apm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__score_details__field_indices_by_name[] = {
  6,   /* field[6] = collected_minerals */
  7,   /* field[7] = collected_vespene */
  8,   /* field[8] = collection_rate_minerals */
  9,   /* field[9] = collection_rate_vespene */
  26,   /* field[26] = current_apm */
  27,   /* field[27] = current_effective_apm */
  12,   /* field[12] = food_used */
  17,   /* field[17] = friendly_fire_minerals */
  18,   /* field[18] = friendly_fire_vespene */
  0,   /* field[0] = idle_production_time */
  1,   /* field[1] = idle_worker_time */
  13,   /* field[13] = killed_minerals */
  5,   /* field[5] = killed_value_structures */
  4,   /* field[4] = killed_value_units */
  14,   /* field[14] = killed_vespene */
  15,   /* field[15] = lost_minerals */
  16,   /* field[16] = lost_vespene */
  10,   /* field[10] = spent_minerals */
  11,   /* field[11] = spent_vespene */
  23,   /* field[23] = total_damage_dealt */
  24,   /* field[24] = total_damage_taken */
  25,   /* field[25] = total_healed */
  21,   /* field[21] = total_used_minerals */
  22,   /* field[22] = total_used_vespene */
  3,   /* field[3] = total_value_structures */
  2,   /* field[2] = total_value_units */
  19,   /* field[19] = used_minerals */
  20,   /* field[20] = used_vespene */
};
static const ProtobufCIntRange sc2_apiprotocol__score_details__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 28 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__score_details__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.ScoreDetails",
  "ScoreDetails",
  "SC2APIProtocol__ScoreDetails",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__ScoreDetails),
  28,
  sc2_apiprotocol__score_details__field_descriptors,
  sc2_apiprotocol__score_details__field_indices_by_name,
  1,  sc2_apiprotocol__score_details__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__score_details__init,
  NULL,NULL,NULL    /* reserved[123] */
};
