/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: s2clientprotocol/ui.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "s2clientprotocol/ui.pb-c.h"
void   sc2_apiprotocol__observation_ui__init
                     (SC2APIProtocol__ObservationUI         *message)
{
  static const SC2APIProtocol__ObservationUI init_value = SC2_APIPROTOCOL__OBSERVATION_UI__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__observation_ui__get_packed_size
                     (const SC2APIProtocol__ObservationUI *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__observation_ui__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__observation_ui__pack
                     (const SC2APIProtocol__ObservationUI *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__observation_ui__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__observation_ui__pack_to_buffer
                     (const SC2APIProtocol__ObservationUI *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__observation_ui__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__ObservationUI *
       sc2_apiprotocol__observation_ui__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__ObservationUI *)
     protobuf_c_message_unpack (&sc2_apiprotocol__observation_ui__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__observation_ui__free_unpacked
                     (SC2APIProtocol__ObservationUI *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__observation_ui__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__control_group__init
                     (SC2APIProtocol__ControlGroup         *message)
{
  static const SC2APIProtocol__ControlGroup init_value = SC2_APIPROTOCOL__CONTROL_GROUP__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__control_group__get_packed_size
                     (const SC2APIProtocol__ControlGroup *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__control_group__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__control_group__pack
                     (const SC2APIProtocol__ControlGroup *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__control_group__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__control_group__pack_to_buffer
                     (const SC2APIProtocol__ControlGroup *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__control_group__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__ControlGroup *
       sc2_apiprotocol__control_group__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__ControlGroup *)
     protobuf_c_message_unpack (&sc2_apiprotocol__control_group__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__control_group__free_unpacked
                     (SC2APIProtocol__ControlGroup *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__control_group__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__unit_info__init
                     (SC2APIProtocol__UnitInfo         *message)
{
  static const SC2APIProtocol__UnitInfo init_value = SC2_APIPROTOCOL__UNIT_INFO__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__unit_info__get_packed_size
                     (const SC2APIProtocol__UnitInfo *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__unit_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__unit_info__pack
                     (const SC2APIProtocol__UnitInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__unit_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__unit_info__pack_to_buffer
                     (const SC2APIProtocol__UnitInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__unit_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__UnitInfo *
       sc2_apiprotocol__unit_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__UnitInfo *)
     protobuf_c_message_unpack (&sc2_apiprotocol__unit_info__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__unit_info__free_unpacked
                     (SC2APIProtocol__UnitInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__unit_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__single_panel__init
                     (SC2APIProtocol__SinglePanel         *message)
{
  static const SC2APIProtocol__SinglePanel init_value = SC2_APIPROTOCOL__SINGLE_PANEL__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__single_panel__get_packed_size
                     (const SC2APIProtocol__SinglePanel *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__single_panel__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__single_panel__pack
                     (const SC2APIProtocol__SinglePanel *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__single_panel__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__single_panel__pack_to_buffer
                     (const SC2APIProtocol__SinglePanel *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__single_panel__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__SinglePanel *
       sc2_apiprotocol__single_panel__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__SinglePanel *)
     protobuf_c_message_unpack (&sc2_apiprotocol__single_panel__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__single_panel__free_unpacked
                     (SC2APIProtocol__SinglePanel *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__single_panel__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__multi_panel__init
                     (SC2APIProtocol__MultiPanel         *message)
{
  static const SC2APIProtocol__MultiPanel init_value = SC2_APIPROTOCOL__MULTI_PANEL__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__multi_panel__get_packed_size
                     (const SC2APIProtocol__MultiPanel *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__multi_panel__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__multi_panel__pack
                     (const SC2APIProtocol__MultiPanel *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__multi_panel__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__multi_panel__pack_to_buffer
                     (const SC2APIProtocol__MultiPanel *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__multi_panel__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__MultiPanel *
       sc2_apiprotocol__multi_panel__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__MultiPanel *)
     protobuf_c_message_unpack (&sc2_apiprotocol__multi_panel__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__multi_panel__free_unpacked
                     (SC2APIProtocol__MultiPanel *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__multi_panel__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__cargo_panel__init
                     (SC2APIProtocol__CargoPanel         *message)
{
  static const SC2APIProtocol__CargoPanel init_value = SC2_APIPROTOCOL__CARGO_PANEL__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__cargo_panel__get_packed_size
                     (const SC2APIProtocol__CargoPanel *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__cargo_panel__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__cargo_panel__pack
                     (const SC2APIProtocol__CargoPanel *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__cargo_panel__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__cargo_panel__pack_to_buffer
                     (const SC2APIProtocol__CargoPanel *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__cargo_panel__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__CargoPanel *
       sc2_apiprotocol__cargo_panel__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__CargoPanel *)
     protobuf_c_message_unpack (&sc2_apiprotocol__cargo_panel__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__cargo_panel__free_unpacked
                     (SC2APIProtocol__CargoPanel *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__cargo_panel__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__build_item__init
                     (SC2APIProtocol__BuildItem         *message)
{
  static const SC2APIProtocol__BuildItem init_value = SC2_APIPROTOCOL__BUILD_ITEM__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__build_item__get_packed_size
                     (const SC2APIProtocol__BuildItem *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__build_item__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__build_item__pack
                     (const SC2APIProtocol__BuildItem *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__build_item__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__build_item__pack_to_buffer
                     (const SC2APIProtocol__BuildItem *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__build_item__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__BuildItem *
       sc2_apiprotocol__build_item__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__BuildItem *)
     protobuf_c_message_unpack (&sc2_apiprotocol__build_item__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__build_item__free_unpacked
                     (SC2APIProtocol__BuildItem *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__build_item__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__production_panel__init
                     (SC2APIProtocol__ProductionPanel         *message)
{
  static const SC2APIProtocol__ProductionPanel init_value = SC2_APIPROTOCOL__PRODUCTION_PANEL__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__production_panel__get_packed_size
                     (const SC2APIProtocol__ProductionPanel *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__production_panel__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__production_panel__pack
                     (const SC2APIProtocol__ProductionPanel *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__production_panel__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__production_panel__pack_to_buffer
                     (const SC2APIProtocol__ProductionPanel *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__production_panel__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__ProductionPanel *
       sc2_apiprotocol__production_panel__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__ProductionPanel *)
     protobuf_c_message_unpack (&sc2_apiprotocol__production_panel__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__production_panel__free_unpacked
                     (SC2APIProtocol__ProductionPanel *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__production_panel__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__action_ui__init
                     (SC2APIProtocol__ActionUI         *message)
{
  static const SC2APIProtocol__ActionUI init_value = SC2_APIPROTOCOL__ACTION_UI__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__action_ui__get_packed_size
                     (const SC2APIProtocol__ActionUI *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_ui__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__action_ui__pack
                     (const SC2APIProtocol__ActionUI *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_ui__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__action_ui__pack_to_buffer
                     (const SC2APIProtocol__ActionUI *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_ui__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__ActionUI *
       sc2_apiprotocol__action_ui__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__ActionUI *)
     protobuf_c_message_unpack (&sc2_apiprotocol__action_ui__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__action_ui__free_unpacked
                     (SC2APIProtocol__ActionUI *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__action_ui__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__action_control_group__init
                     (SC2APIProtocol__ActionControlGroup         *message)
{
  static const SC2APIProtocol__ActionControlGroup init_value = SC2_APIPROTOCOL__ACTION_CONTROL_GROUP__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__action_control_group__get_packed_size
                     (const SC2APIProtocol__ActionControlGroup *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_control_group__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__action_control_group__pack
                     (const SC2APIProtocol__ActionControlGroup *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_control_group__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__action_control_group__pack_to_buffer
                     (const SC2APIProtocol__ActionControlGroup *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_control_group__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__ActionControlGroup *
       sc2_apiprotocol__action_control_group__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__ActionControlGroup *)
     protobuf_c_message_unpack (&sc2_apiprotocol__action_control_group__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__action_control_group__free_unpacked
                     (SC2APIProtocol__ActionControlGroup *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__action_control_group__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__action_select_army__init
                     (SC2APIProtocol__ActionSelectArmy         *message)
{
  static const SC2APIProtocol__ActionSelectArmy init_value = SC2_APIPROTOCOL__ACTION_SELECT_ARMY__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__action_select_army__get_packed_size
                     (const SC2APIProtocol__ActionSelectArmy *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_select_army__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__action_select_army__pack
                     (const SC2APIProtocol__ActionSelectArmy *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_select_army__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__action_select_army__pack_to_buffer
                     (const SC2APIProtocol__ActionSelectArmy *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_select_army__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__ActionSelectArmy *
       sc2_apiprotocol__action_select_army__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__ActionSelectArmy *)
     protobuf_c_message_unpack (&sc2_apiprotocol__action_select_army__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__action_select_army__free_unpacked
                     (SC2APIProtocol__ActionSelectArmy *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__action_select_army__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__action_select_warp_gates__init
                     (SC2APIProtocol__ActionSelectWarpGates         *message)
{
  static const SC2APIProtocol__ActionSelectWarpGates init_value = SC2_APIPROTOCOL__ACTION_SELECT_WARP_GATES__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__action_select_warp_gates__get_packed_size
                     (const SC2APIProtocol__ActionSelectWarpGates *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_select_warp_gates__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__action_select_warp_gates__pack
                     (const SC2APIProtocol__ActionSelectWarpGates *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_select_warp_gates__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__action_select_warp_gates__pack_to_buffer
                     (const SC2APIProtocol__ActionSelectWarpGates *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_select_warp_gates__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__ActionSelectWarpGates *
       sc2_apiprotocol__action_select_warp_gates__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__ActionSelectWarpGates *)
     protobuf_c_message_unpack (&sc2_apiprotocol__action_select_warp_gates__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__action_select_warp_gates__free_unpacked
                     (SC2APIProtocol__ActionSelectWarpGates *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__action_select_warp_gates__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__action_select_larva__init
                     (SC2APIProtocol__ActionSelectLarva         *message)
{
  static const SC2APIProtocol__ActionSelectLarva init_value = SC2_APIPROTOCOL__ACTION_SELECT_LARVA__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__action_select_larva__get_packed_size
                     (const SC2APIProtocol__ActionSelectLarva *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_select_larva__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__action_select_larva__pack
                     (const SC2APIProtocol__ActionSelectLarva *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_select_larva__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__action_select_larva__pack_to_buffer
                     (const SC2APIProtocol__ActionSelectLarva *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_select_larva__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__ActionSelectLarva *
       sc2_apiprotocol__action_select_larva__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__ActionSelectLarva *)
     protobuf_c_message_unpack (&sc2_apiprotocol__action_select_larva__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__action_select_larva__free_unpacked
                     (SC2APIProtocol__ActionSelectLarva *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__action_select_larva__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__action_select_idle_worker__init
                     (SC2APIProtocol__ActionSelectIdleWorker         *message)
{
  static const SC2APIProtocol__ActionSelectIdleWorker init_value = SC2_APIPROTOCOL__ACTION_SELECT_IDLE_WORKER__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__action_select_idle_worker__get_packed_size
                     (const SC2APIProtocol__ActionSelectIdleWorker *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_select_idle_worker__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__action_select_idle_worker__pack
                     (const SC2APIProtocol__ActionSelectIdleWorker *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_select_idle_worker__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__action_select_idle_worker__pack_to_buffer
                     (const SC2APIProtocol__ActionSelectIdleWorker *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_select_idle_worker__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__ActionSelectIdleWorker *
       sc2_apiprotocol__action_select_idle_worker__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__ActionSelectIdleWorker *)
     protobuf_c_message_unpack (&sc2_apiprotocol__action_select_idle_worker__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__action_select_idle_worker__free_unpacked
                     (SC2APIProtocol__ActionSelectIdleWorker *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__action_select_idle_worker__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__action_multi_panel__init
                     (SC2APIProtocol__ActionMultiPanel         *message)
{
  static const SC2APIProtocol__ActionMultiPanel init_value = SC2_APIPROTOCOL__ACTION_MULTI_PANEL__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__action_multi_panel__get_packed_size
                     (const SC2APIProtocol__ActionMultiPanel *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_multi_panel__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__action_multi_panel__pack
                     (const SC2APIProtocol__ActionMultiPanel *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_multi_panel__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__action_multi_panel__pack_to_buffer
                     (const SC2APIProtocol__ActionMultiPanel *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_multi_panel__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__ActionMultiPanel *
       sc2_apiprotocol__action_multi_panel__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__ActionMultiPanel *)
     protobuf_c_message_unpack (&sc2_apiprotocol__action_multi_panel__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__action_multi_panel__free_unpacked
                     (SC2APIProtocol__ActionMultiPanel *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__action_multi_panel__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__action_cargo_panel_unload__init
                     (SC2APIProtocol__ActionCargoPanelUnload         *message)
{
  static const SC2APIProtocol__ActionCargoPanelUnload init_value = SC2_APIPROTOCOL__ACTION_CARGO_PANEL_UNLOAD__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__action_cargo_panel_unload__get_packed_size
                     (const SC2APIProtocol__ActionCargoPanelUnload *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_cargo_panel_unload__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__action_cargo_panel_unload__pack
                     (const SC2APIProtocol__ActionCargoPanelUnload *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_cargo_panel_unload__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__action_cargo_panel_unload__pack_to_buffer
                     (const SC2APIProtocol__ActionCargoPanelUnload *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_cargo_panel_unload__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__ActionCargoPanelUnload *
       sc2_apiprotocol__action_cargo_panel_unload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__ActionCargoPanelUnload *)
     protobuf_c_message_unpack (&sc2_apiprotocol__action_cargo_panel_unload__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__action_cargo_panel_unload__free_unpacked
                     (SC2APIProtocol__ActionCargoPanelUnload *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__action_cargo_panel_unload__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__action_production_panel_remove_from_queue__init
                     (SC2APIProtocol__ActionProductionPanelRemoveFromQueue         *message)
{
  static const SC2APIProtocol__ActionProductionPanelRemoveFromQueue init_value = SC2_APIPROTOCOL__ACTION_PRODUCTION_PANEL_REMOVE_FROM_QUEUE__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__action_production_panel_remove_from_queue__get_packed_size
                     (const SC2APIProtocol__ActionProductionPanelRemoveFromQueue *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_production_panel_remove_from_queue__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__action_production_panel_remove_from_queue__pack
                     (const SC2APIProtocol__ActionProductionPanelRemoveFromQueue *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_production_panel_remove_from_queue__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__action_production_panel_remove_from_queue__pack_to_buffer
                     (const SC2APIProtocol__ActionProductionPanelRemoveFromQueue *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_production_panel_remove_from_queue__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__ActionProductionPanelRemoveFromQueue *
       sc2_apiprotocol__action_production_panel_remove_from_queue__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__ActionProductionPanelRemoveFromQueue *)
     protobuf_c_message_unpack (&sc2_apiprotocol__action_production_panel_remove_from_queue__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__action_production_panel_remove_from_queue__free_unpacked
                     (SC2APIProtocol__ActionProductionPanelRemoveFromQueue *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__action_production_panel_remove_from_queue__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sc2_apiprotocol__action_toggle_autocast__init
                     (SC2APIProtocol__ActionToggleAutocast         *message)
{
  static const SC2APIProtocol__ActionToggleAutocast init_value = SC2_APIPROTOCOL__ACTION_TOGGLE_AUTOCAST__INIT;
  *message = init_value;
}
size_t sc2_apiprotocol__action_toggle_autocast__get_packed_size
                     (const SC2APIProtocol__ActionToggleAutocast *message)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_toggle_autocast__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sc2_apiprotocol__action_toggle_autocast__pack
                     (const SC2APIProtocol__ActionToggleAutocast *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_toggle_autocast__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sc2_apiprotocol__action_toggle_autocast__pack_to_buffer
                     (const SC2APIProtocol__ActionToggleAutocast *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sc2_apiprotocol__action_toggle_autocast__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SC2APIProtocol__ActionToggleAutocast *
       sc2_apiprotocol__action_toggle_autocast__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SC2APIProtocol__ActionToggleAutocast *)
     protobuf_c_message_unpack (&sc2_apiprotocol__action_toggle_autocast__descriptor,
                                allocator, len, data);
}
void   sc2_apiprotocol__action_toggle_autocast__free_unpacked
                     (SC2APIProtocol__ActionToggleAutocast *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sc2_apiprotocol__action_toggle_autocast__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor sc2_apiprotocol__observation_ui__field_descriptors[5] =
{
  {
    "groups",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__ObservationUI, n_groups),
    offsetof(SC2APIProtocol__ObservationUI, groups),
    &sc2_apiprotocol__control_group__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "single",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__ObservationUI, panel_case),
    offsetof(SC2APIProtocol__ObservationUI, single),
    &sc2_apiprotocol__single_panel__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "multi",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__ObservationUI, panel_case),
    offsetof(SC2APIProtocol__ObservationUI, multi),
    &sc2_apiprotocol__multi_panel__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cargo",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__ObservationUI, panel_case),
    offsetof(SC2APIProtocol__ObservationUI, cargo),
    &sc2_apiprotocol__cargo_panel__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "production",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__ObservationUI, panel_case),
    offsetof(SC2APIProtocol__ObservationUI, production),
    &sc2_apiprotocol__production_panel__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__observation_ui__field_indices_by_name[] = {
  3,   /* field[3] = cargo */
  0,   /* field[0] = groups */
  2,   /* field[2] = multi */
  4,   /* field[4] = production */
  1,   /* field[1] = single */
};
static const ProtobufCIntRange sc2_apiprotocol__observation_ui__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__observation_ui__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.ObservationUI",
  "ObservationUI",
  "SC2APIProtocol__ObservationUI",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__ObservationUI),
  5,
  sc2_apiprotocol__observation_ui__field_descriptors,
  sc2_apiprotocol__observation_ui__field_indices_by_name,
  1,  sc2_apiprotocol__observation_ui__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__observation_ui__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__control_group__field_descriptors[3] =
{
  {
    "control_group_index",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SC2APIProtocol__ControlGroup, has_control_group_index),
    offsetof(SC2APIProtocol__ControlGroup, control_group_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "leader_unit_type",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SC2APIProtocol__ControlGroup, has_leader_unit_type),
    offsetof(SC2APIProtocol__ControlGroup, leader_unit_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SC2APIProtocol__ControlGroup, has_count),
    offsetof(SC2APIProtocol__ControlGroup, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__control_group__field_indices_by_name[] = {
  0,   /* field[0] = control_group_index */
  2,   /* field[2] = count */
  1,   /* field[1] = leader_unit_type */
};
static const ProtobufCIntRange sc2_apiprotocol__control_group__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__control_group__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.ControlGroup",
  "ControlGroup",
  "SC2APIProtocol__ControlGroup",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__ControlGroup),
  3,
  sc2_apiprotocol__control_group__field_descriptors,
  sc2_apiprotocol__control_group__field_indices_by_name,
  1,  sc2_apiprotocol__control_group__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__control_group__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__unit_info__field_descriptors[11] =
{
  {
    "unit_type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SC2APIProtocol__UnitInfo, has_unit_type),
    offsetof(SC2APIProtocol__UnitInfo, unit_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "player_relative",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SC2APIProtocol__UnitInfo, has_player_relative),
    offsetof(SC2APIProtocol__UnitInfo, player_relative),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "health",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SC2APIProtocol__UnitInfo, has_health),
    offsetof(SC2APIProtocol__UnitInfo, health),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "shields",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SC2APIProtocol__UnitInfo, has_shields),
    offsetof(SC2APIProtocol__UnitInfo, shields),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "energy",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SC2APIProtocol__UnitInfo, has_energy),
    offsetof(SC2APIProtocol__UnitInfo, energy),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "transport_slots_taken",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SC2APIProtocol__UnitInfo, has_transport_slots_taken),
    offsetof(SC2APIProtocol__UnitInfo, transport_slots_taken),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "build_progress",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__UnitInfo, has_build_progress),
    offsetof(SC2APIProtocol__UnitInfo, build_progress),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "add_on",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__UnitInfo, add_on),
    &sc2_apiprotocol__unit_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_health",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SC2APIProtocol__UnitInfo, has_max_health),
    offsetof(SC2APIProtocol__UnitInfo, max_health),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_shields",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SC2APIProtocol__UnitInfo, has_max_shields),
    offsetof(SC2APIProtocol__UnitInfo, max_shields),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_energy",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SC2APIProtocol__UnitInfo, has_max_energy),
    offsetof(SC2APIProtocol__UnitInfo, max_energy),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__unit_info__field_indices_by_name[] = {
  7,   /* field[7] = add_on */
  6,   /* field[6] = build_progress */
  4,   /* field[4] = energy */
  2,   /* field[2] = health */
  10,   /* field[10] = max_energy */
  8,   /* field[8] = max_health */
  9,   /* field[9] = max_shields */
  1,   /* field[1] = player_relative */
  3,   /* field[3] = shields */
  5,   /* field[5] = transport_slots_taken */
  0,   /* field[0] = unit_type */
};
static const ProtobufCIntRange sc2_apiprotocol__unit_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__unit_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.UnitInfo",
  "UnitInfo",
  "SC2APIProtocol__UnitInfo",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__UnitInfo),
  11,
  sc2_apiprotocol__unit_info__field_descriptors,
  sc2_apiprotocol__unit_info__field_indices_by_name,
  1,  sc2_apiprotocol__unit_info__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__unit_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__single_panel__field_descriptors[5] =
{
  {
    "unit",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__SinglePanel, unit),
    &sc2_apiprotocol__unit_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attack_upgrade_level",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SC2APIProtocol__SinglePanel, has_attack_upgrade_level),
    offsetof(SC2APIProtocol__SinglePanel, attack_upgrade_level),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "armor_upgrade_level",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SC2APIProtocol__SinglePanel, has_armor_upgrade_level),
    offsetof(SC2APIProtocol__SinglePanel, armor_upgrade_level),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "shield_upgrade_level",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SC2APIProtocol__SinglePanel, has_shield_upgrade_level),
    offsetof(SC2APIProtocol__SinglePanel, shield_upgrade_level),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "buffs",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SC2APIProtocol__SinglePanel, n_buffs),
    offsetof(SC2APIProtocol__SinglePanel, buffs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__single_panel__field_indices_by_name[] = {
  2,   /* field[2] = armor_upgrade_level */
  1,   /* field[1] = attack_upgrade_level */
  4,   /* field[4] = buffs */
  3,   /* field[3] = shield_upgrade_level */
  0,   /* field[0] = unit */
};
static const ProtobufCIntRange sc2_apiprotocol__single_panel__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__single_panel__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.SinglePanel",
  "SinglePanel",
  "SC2APIProtocol__SinglePanel",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__SinglePanel),
  5,
  sc2_apiprotocol__single_panel__field_descriptors,
  sc2_apiprotocol__single_panel__field_indices_by_name,
  1,  sc2_apiprotocol__single_panel__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__single_panel__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__multi_panel__field_descriptors[1] =
{
  {
    "units",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__MultiPanel, n_units),
    offsetof(SC2APIProtocol__MultiPanel, units),
    &sc2_apiprotocol__unit_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__multi_panel__field_indices_by_name[] = {
  0,   /* field[0] = units */
};
static const ProtobufCIntRange sc2_apiprotocol__multi_panel__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__multi_panel__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.MultiPanel",
  "MultiPanel",
  "SC2APIProtocol__MultiPanel",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__MultiPanel),
  1,
  sc2_apiprotocol__multi_panel__field_descriptors,
  sc2_apiprotocol__multi_panel__field_indices_by_name,
  1,  sc2_apiprotocol__multi_panel__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__multi_panel__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__cargo_panel__field_descriptors[3] =
{
  {
    "unit",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__CargoPanel, unit),
    &sc2_apiprotocol__unit_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "passengers",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__CargoPanel, n_passengers),
    offsetof(SC2APIProtocol__CargoPanel, passengers),
    &sc2_apiprotocol__unit_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "slots_available",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SC2APIProtocol__CargoPanel, has_slots_available),
    offsetof(SC2APIProtocol__CargoPanel, slots_available),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__cargo_panel__field_indices_by_name[] = {
  1,   /* field[1] = passengers */
  2,   /* field[2] = slots_available */
  0,   /* field[0] = unit */
};
static const ProtobufCIntRange sc2_apiprotocol__cargo_panel__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__cargo_panel__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.CargoPanel",
  "CargoPanel",
  "SC2APIProtocol__CargoPanel",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__CargoPanel),
  3,
  sc2_apiprotocol__cargo_panel__field_descriptors,
  sc2_apiprotocol__cargo_panel__field_indices_by_name,
  1,  sc2_apiprotocol__cargo_panel__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__cargo_panel__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__build_item__field_descriptors[2] =
{
  {
    "ability_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SC2APIProtocol__BuildItem, has_ability_id),
    offsetof(SC2APIProtocol__BuildItem, ability_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "build_progress",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SC2APIProtocol__BuildItem, has_build_progress),
    offsetof(SC2APIProtocol__BuildItem, build_progress),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__build_item__field_indices_by_name[] = {
  0,   /* field[0] = ability_id */
  1,   /* field[1] = build_progress */
};
static const ProtobufCIntRange sc2_apiprotocol__build_item__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__build_item__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.BuildItem",
  "BuildItem",
  "SC2APIProtocol__BuildItem",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__BuildItem),
  2,
  sc2_apiprotocol__build_item__field_descriptors,
  sc2_apiprotocol__build_item__field_indices_by_name,
  1,  sc2_apiprotocol__build_item__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__build_item__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__production_panel__field_descriptors[3] =
{
  {
    "unit",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SC2APIProtocol__ProductionPanel, unit),
    &sc2_apiprotocol__unit_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "build_queue",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__ProductionPanel, n_build_queue),
    offsetof(SC2APIProtocol__ProductionPanel, build_queue),
    &sc2_apiprotocol__unit_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "production_queue",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__ProductionPanel, n_production_queue),
    offsetof(SC2APIProtocol__ProductionPanel, production_queue),
    &sc2_apiprotocol__build_item__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__production_panel__field_indices_by_name[] = {
  1,   /* field[1] = build_queue */
  2,   /* field[2] = production_queue */
  0,   /* field[0] = unit */
};
static const ProtobufCIntRange sc2_apiprotocol__production_panel__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__production_panel__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.ProductionPanel",
  "ProductionPanel",
  "SC2APIProtocol__ProductionPanel",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__ProductionPanel),
  3,
  sc2_apiprotocol__production_panel__field_descriptors,
  sc2_apiprotocol__production_panel__field_indices_by_name,
  1,  sc2_apiprotocol__production_panel__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__production_panel__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__action_ui__field_descriptors[9] =
{
  {
    "control_group",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__ActionUI, action_case),
    offsetof(SC2APIProtocol__ActionUI, control_group),
    &sc2_apiprotocol__action_control_group__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "select_army",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__ActionUI, action_case),
    offsetof(SC2APIProtocol__ActionUI, select_army),
    &sc2_apiprotocol__action_select_army__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "select_warp_gates",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__ActionUI, action_case),
    offsetof(SC2APIProtocol__ActionUI, select_warp_gates),
    &sc2_apiprotocol__action_select_warp_gates__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "select_larva",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__ActionUI, action_case),
    offsetof(SC2APIProtocol__ActionUI, select_larva),
    &sc2_apiprotocol__action_select_larva__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "select_idle_worker",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__ActionUI, action_case),
    offsetof(SC2APIProtocol__ActionUI, select_idle_worker),
    &sc2_apiprotocol__action_select_idle_worker__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "multi_panel",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__ActionUI, action_case),
    offsetof(SC2APIProtocol__ActionUI, multi_panel),
    &sc2_apiprotocol__action_multi_panel__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cargo_panel",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__ActionUI, action_case),
    offsetof(SC2APIProtocol__ActionUI, cargo_panel),
    &sc2_apiprotocol__action_cargo_panel_unload__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "production_panel",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__ActionUI, action_case),
    offsetof(SC2APIProtocol__ActionUI, production_panel),
    &sc2_apiprotocol__action_production_panel_remove_from_queue__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "toggle_autocast",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SC2APIProtocol__ActionUI, action_case),
    offsetof(SC2APIProtocol__ActionUI, toggle_autocast),
    &sc2_apiprotocol__action_toggle_autocast__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__action_ui__field_indices_by_name[] = {
  6,   /* field[6] = cargo_panel */
  0,   /* field[0] = control_group */
  5,   /* field[5] = multi_panel */
  7,   /* field[7] = production_panel */
  1,   /* field[1] = select_army */
  4,   /* field[4] = select_idle_worker */
  3,   /* field[3] = select_larva */
  2,   /* field[2] = select_warp_gates */
  8,   /* field[8] = toggle_autocast */
};
static const ProtobufCIntRange sc2_apiprotocol__action_ui__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__action_ui__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.ActionUI",
  "ActionUI",
  "SC2APIProtocol__ActionUI",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__ActionUI),
  9,
  sc2_apiprotocol__action_ui__field_descriptors,
  sc2_apiprotocol__action_ui__field_indices_by_name,
  1,  sc2_apiprotocol__action_ui__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__action_ui__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue sc2_apiprotocol__action_control_group__control_group_action__enum_values_by_number[5] =
{
  { "Recall", "SC2_APIPROTOCOL__ACTION_CONTROL_GROUP__CONTROL_GROUP_ACTION__Recall", 1 },
  { "Set", "SC2_APIPROTOCOL__ACTION_CONTROL_GROUP__CONTROL_GROUP_ACTION__Set", 2 },
  { "Append", "SC2_APIPROTOCOL__ACTION_CONTROL_GROUP__CONTROL_GROUP_ACTION__Append", 3 },
  { "SetAndSteal", "SC2_APIPROTOCOL__ACTION_CONTROL_GROUP__CONTROL_GROUP_ACTION__SetAndSteal", 4 },
  { "AppendAndSteal", "SC2_APIPROTOCOL__ACTION_CONTROL_GROUP__CONTROL_GROUP_ACTION__AppendAndSteal", 5 },
};
static const ProtobufCIntRange sc2_apiprotocol__action_control_group__control_group_action__value_ranges[] = {
{1, 0},{0, 5}
};
static const ProtobufCEnumValueIndex sc2_apiprotocol__action_control_group__control_group_action__enum_values_by_name[5] =
{
  { "Append", 2 },
  { "AppendAndSteal", 4 },
  { "Recall", 0 },
  { "Set", 1 },
  { "SetAndSteal", 3 },
};
const ProtobufCEnumDescriptor sc2_apiprotocol__action_control_group__control_group_action__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.ActionControlGroup.ControlGroupAction",
  "ControlGroupAction",
  "SC2APIProtocol__ActionControlGroup__ControlGroupAction",
  "SC2APIProtocol",
  5,
  sc2_apiprotocol__action_control_group__control_group_action__enum_values_by_number,
  5,
  sc2_apiprotocol__action_control_group__control_group_action__enum_values_by_name,
  1,
  sc2_apiprotocol__action_control_group__control_group_action__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__action_control_group__field_descriptors[2] =
{
  {
    "action",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(SC2APIProtocol__ActionControlGroup, has_action),
    offsetof(SC2APIProtocol__ActionControlGroup, action),
    &sc2_apiprotocol__action_control_group__control_group_action__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "control_group_index",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SC2APIProtocol__ActionControlGroup, has_control_group_index),
    offsetof(SC2APIProtocol__ActionControlGroup, control_group_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__action_control_group__field_indices_by_name[] = {
  0,   /* field[0] = action */
  1,   /* field[1] = control_group_index */
};
static const ProtobufCIntRange sc2_apiprotocol__action_control_group__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__action_control_group__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.ActionControlGroup",
  "ActionControlGroup",
  "SC2APIProtocol__ActionControlGroup",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__ActionControlGroup),
  2,
  sc2_apiprotocol__action_control_group__field_descriptors,
  sc2_apiprotocol__action_control_group__field_indices_by_name,
  1,  sc2_apiprotocol__action_control_group__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__action_control_group__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__action_select_army__field_descriptors[1] =
{
  {
    "selection_add",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(SC2APIProtocol__ActionSelectArmy, has_selection_add),
    offsetof(SC2APIProtocol__ActionSelectArmy, selection_add),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__action_select_army__field_indices_by_name[] = {
  0,   /* field[0] = selection_add */
};
static const ProtobufCIntRange sc2_apiprotocol__action_select_army__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__action_select_army__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.ActionSelectArmy",
  "ActionSelectArmy",
  "SC2APIProtocol__ActionSelectArmy",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__ActionSelectArmy),
  1,
  sc2_apiprotocol__action_select_army__field_descriptors,
  sc2_apiprotocol__action_select_army__field_indices_by_name,
  1,  sc2_apiprotocol__action_select_army__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__action_select_army__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__action_select_warp_gates__field_descriptors[1] =
{
  {
    "selection_add",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(SC2APIProtocol__ActionSelectWarpGates, has_selection_add),
    offsetof(SC2APIProtocol__ActionSelectWarpGates, selection_add),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__action_select_warp_gates__field_indices_by_name[] = {
  0,   /* field[0] = selection_add */
};
static const ProtobufCIntRange sc2_apiprotocol__action_select_warp_gates__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__action_select_warp_gates__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.ActionSelectWarpGates",
  "ActionSelectWarpGates",
  "SC2APIProtocol__ActionSelectWarpGates",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__ActionSelectWarpGates),
  1,
  sc2_apiprotocol__action_select_warp_gates__field_descriptors,
  sc2_apiprotocol__action_select_warp_gates__field_indices_by_name,
  1,  sc2_apiprotocol__action_select_warp_gates__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__action_select_warp_gates__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define sc2_apiprotocol__action_select_larva__field_descriptors NULL
#define sc2_apiprotocol__action_select_larva__field_indices_by_name NULL
#define sc2_apiprotocol__action_select_larva__number_ranges NULL
const ProtobufCMessageDescriptor sc2_apiprotocol__action_select_larva__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.ActionSelectLarva",
  "ActionSelectLarva",
  "SC2APIProtocol__ActionSelectLarva",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__ActionSelectLarva),
  0,
  sc2_apiprotocol__action_select_larva__field_descriptors,
  sc2_apiprotocol__action_select_larva__field_indices_by_name,
  0,  sc2_apiprotocol__action_select_larva__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__action_select_larva__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue sc2_apiprotocol__action_select_idle_worker__type__enum_values_by_number[4] =
{
  { "Set", "SC2_APIPROTOCOL__ACTION_SELECT_IDLE_WORKER__TYPE__Set", 1 },
  { "Add", "SC2_APIPROTOCOL__ACTION_SELECT_IDLE_WORKER__TYPE__Add", 2 },
  { "All", "SC2_APIPROTOCOL__ACTION_SELECT_IDLE_WORKER__TYPE__All", 3 },
  { "AddAll", "SC2_APIPROTOCOL__ACTION_SELECT_IDLE_WORKER__TYPE__AddAll", 4 },
};
static const ProtobufCIntRange sc2_apiprotocol__action_select_idle_worker__type__value_ranges[] = {
{1, 0},{0, 4}
};
static const ProtobufCEnumValueIndex sc2_apiprotocol__action_select_idle_worker__type__enum_values_by_name[4] =
{
  { "Add", 1 },
  { "AddAll", 3 },
  { "All", 2 },
  { "Set", 0 },
};
const ProtobufCEnumDescriptor sc2_apiprotocol__action_select_idle_worker__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.ActionSelectIdleWorker.Type",
  "Type",
  "SC2APIProtocol__ActionSelectIdleWorker__Type",
  "SC2APIProtocol",
  4,
  sc2_apiprotocol__action_select_idle_worker__type__enum_values_by_number,
  4,
  sc2_apiprotocol__action_select_idle_worker__type__enum_values_by_name,
  1,
  sc2_apiprotocol__action_select_idle_worker__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__action_select_idle_worker__field_descriptors[1] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(SC2APIProtocol__ActionSelectIdleWorker, has_type),
    offsetof(SC2APIProtocol__ActionSelectIdleWorker, type),
    &sc2_apiprotocol__action_select_idle_worker__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__action_select_idle_worker__field_indices_by_name[] = {
  0,   /* field[0] = type */
};
static const ProtobufCIntRange sc2_apiprotocol__action_select_idle_worker__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__action_select_idle_worker__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.ActionSelectIdleWorker",
  "ActionSelectIdleWorker",
  "SC2APIProtocol__ActionSelectIdleWorker",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__ActionSelectIdleWorker),
  1,
  sc2_apiprotocol__action_select_idle_worker__field_descriptors,
  sc2_apiprotocol__action_select_idle_worker__field_indices_by_name,
  1,  sc2_apiprotocol__action_select_idle_worker__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__action_select_idle_worker__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue sc2_apiprotocol__action_multi_panel__type__enum_values_by_number[4] =
{
  { "SingleSelect", "SC2_APIPROTOCOL__ACTION_MULTI_PANEL__TYPE__SingleSelect", 1 },
  { "DeselectUnit", "SC2_APIPROTOCOL__ACTION_MULTI_PANEL__TYPE__DeselectUnit", 2 },
  { "SelectAllOfType", "SC2_APIPROTOCOL__ACTION_MULTI_PANEL__TYPE__SelectAllOfType", 3 },
  { "DeselectAllOfType", "SC2_APIPROTOCOL__ACTION_MULTI_PANEL__TYPE__DeselectAllOfType", 4 },
};
static const ProtobufCIntRange sc2_apiprotocol__action_multi_panel__type__value_ranges[] = {
{1, 0},{0, 4}
};
static const ProtobufCEnumValueIndex sc2_apiprotocol__action_multi_panel__type__enum_values_by_name[4] =
{
  { "DeselectAllOfType", 3 },
  { "DeselectUnit", 1 },
  { "SelectAllOfType", 2 },
  { "SingleSelect", 0 },
};
const ProtobufCEnumDescriptor sc2_apiprotocol__action_multi_panel__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.ActionMultiPanel.Type",
  "Type",
  "SC2APIProtocol__ActionMultiPanel__Type",
  "SC2APIProtocol",
  4,
  sc2_apiprotocol__action_multi_panel__type__enum_values_by_number,
  4,
  sc2_apiprotocol__action_multi_panel__type__enum_values_by_name,
  1,
  sc2_apiprotocol__action_multi_panel__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__action_multi_panel__field_descriptors[2] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(SC2APIProtocol__ActionMultiPanel, has_type),
    offsetof(SC2APIProtocol__ActionMultiPanel, type),
    &sc2_apiprotocol__action_multi_panel__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unit_index",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SC2APIProtocol__ActionMultiPanel, has_unit_index),
    offsetof(SC2APIProtocol__ActionMultiPanel, unit_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__action_multi_panel__field_indices_by_name[] = {
  0,   /* field[0] = type */
  1,   /* field[1] = unit_index */
};
static const ProtobufCIntRange sc2_apiprotocol__action_multi_panel__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__action_multi_panel__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.ActionMultiPanel",
  "ActionMultiPanel",
  "SC2APIProtocol__ActionMultiPanel",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__ActionMultiPanel),
  2,
  sc2_apiprotocol__action_multi_panel__field_descriptors,
  sc2_apiprotocol__action_multi_panel__field_indices_by_name,
  1,  sc2_apiprotocol__action_multi_panel__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__action_multi_panel__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__action_cargo_panel_unload__field_descriptors[1] =
{
  {
    "unit_index",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SC2APIProtocol__ActionCargoPanelUnload, has_unit_index),
    offsetof(SC2APIProtocol__ActionCargoPanelUnload, unit_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__action_cargo_panel_unload__field_indices_by_name[] = {
  0,   /* field[0] = unit_index */
};
static const ProtobufCIntRange sc2_apiprotocol__action_cargo_panel_unload__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__action_cargo_panel_unload__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.ActionCargoPanelUnload",
  "ActionCargoPanelUnload",
  "SC2APIProtocol__ActionCargoPanelUnload",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__ActionCargoPanelUnload),
  1,
  sc2_apiprotocol__action_cargo_panel_unload__field_descriptors,
  sc2_apiprotocol__action_cargo_panel_unload__field_indices_by_name,
  1,  sc2_apiprotocol__action_cargo_panel_unload__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__action_cargo_panel_unload__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__action_production_panel_remove_from_queue__field_descriptors[1] =
{
  {
    "unit_index",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SC2APIProtocol__ActionProductionPanelRemoveFromQueue, has_unit_index),
    offsetof(SC2APIProtocol__ActionProductionPanelRemoveFromQueue, unit_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__action_production_panel_remove_from_queue__field_indices_by_name[] = {
  0,   /* field[0] = unit_index */
};
static const ProtobufCIntRange sc2_apiprotocol__action_production_panel_remove_from_queue__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__action_production_panel_remove_from_queue__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.ActionProductionPanelRemoveFromQueue",
  "ActionProductionPanelRemoveFromQueue",
  "SC2APIProtocol__ActionProductionPanelRemoveFromQueue",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__ActionProductionPanelRemoveFromQueue),
  1,
  sc2_apiprotocol__action_production_panel_remove_from_queue__field_descriptors,
  sc2_apiprotocol__action_production_panel_remove_from_queue__field_indices_by_name,
  1,  sc2_apiprotocol__action_production_panel_remove_from_queue__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__action_production_panel_remove_from_queue__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sc2_apiprotocol__action_toggle_autocast__field_descriptors[1] =
{
  {
    "ability_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SC2APIProtocol__ActionToggleAutocast, has_ability_id),
    offsetof(SC2APIProtocol__ActionToggleAutocast, ability_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sc2_apiprotocol__action_toggle_autocast__field_indices_by_name[] = {
  0,   /* field[0] = ability_id */
};
static const ProtobufCIntRange sc2_apiprotocol__action_toggle_autocast__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor sc2_apiprotocol__action_toggle_autocast__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SC2APIProtocol.ActionToggleAutocast",
  "ActionToggleAutocast",
  "SC2APIProtocol__ActionToggleAutocast",
  "SC2APIProtocol",
  sizeof(SC2APIProtocol__ActionToggleAutocast),
  1,
  sc2_apiprotocol__action_toggle_autocast__field_descriptors,
  sc2_apiprotocol__action_toggle_autocast__field_indices_by_name,
  1,  sc2_apiprotocol__action_toggle_autocast__number_ranges,
  (ProtobufCMessageInit) sc2_apiprotocol__action_toggle_autocast__init,
  NULL,NULL,NULL    /* reserved[123] */
};
